#!/usr/bin/env bash
# build.sh - assemble the vendorable CyberOS payload into dist/cyberos/.
# init.sh lays this out under a target repo's gitignored .cyberos/, by module:
#   .cyberos/cuo/     - the FR workflow engine (ship-feature-requests + doctrine + status
#                       contract + author/audit skills + gates + templates)
#   .cyberos/memory/  - the memory module (Layer-1 protocol + schema + invariants)
#   .cyberos/plugin/  - the Claude/Cowork plugin
# Best-effort: the three normative docs always vendor (doc-driven mode). Author/audit skill
# bodies and caf tooling vendor only if present (full mode); otherwise the reduced-profile
# floor applies (the target repo's own build/lint/test + code review + the two human gates).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"                 # tools/cyberos-init
repo="$(cd "$here/../.." && pwd)"                      # cyberos repo root
out="${1:-$repo/dist/cyberos}"

echo "cyberos-init: assembling payload into $out"
rm -rf "$out"
mkdir -p "$out/cuo/skills" "$out/cuo/gates/caf" "$out/cuo/templates" "$out/memory"

# --- cuo module: the workflow engine ---
cp "$repo/modules/cuo/chief-technology-officer/workflows/ship-feature-requests.md" "$out/cuo/ship-feature-requests.md"
cp "$repo/modules/cuo/EXECUTION-DISCIPLINE.md"                                       "$out/cuo/EXECUTION-DISCIPLINE.md"
cp "$repo/modules/skill/contracts/feature-request/STATUS-REFERENCE.md"              "$out/cuo/STATUS-REFERENCE.md"
cp "$here/gates/run-gates.sh"                                                        "$out/cuo/gates/run-gates.sh"
cp -R "$here/templates/." "$out/cuo/templates/"

skills="repo-context-map-author repo-context-map-audit architecture-decision-record-author architecture-decision-record-audit edge-case-matrix-author edge-case-matrix-audit mock-contract-test-author mock-contract-test-audit implementation-plan-author implementation-plan-audit observability-injection-author observability-injection-audit backlog-state-update-author backlog-state-update-audit code-review-author code-review-audit coverage-gate-author coverage-gate-audit feature-request-audit"
vendored_skills=0
for s in $skills; do
  if [ -d "$repo/modules/skill/$s" ]; then
    cp -R "$repo/modules/skill/$s" "$out/cuo/skills/$s"
    vendored_skills=$((vendored_skills + 1))
  fi
done

caf_vendored="no"
if [ -f "$repo/scripts/caf_gate.sh" ] && [ -d "$repo/tools/caf" ]; then
  cp "$repo/scripts/caf_gate.sh" "$out/cuo/gates/caf/caf_gate.sh"
  cp -R "$repo/tools/caf" "$out/cuo/gates/caf/caf"
  caf_vendored="yes"
fi

# --- memory module: Layer-1 protocol + schema + invariants ---
cp "$repo/AGENTS.md" "$out/memory/AGENTS.md"
memory_vendored="protocol"
[ -f "$repo/modules/memory/memory.schema.json" ]    && { cp "$repo/modules/memory/memory.schema.json"    "$out/memory/memory.schema.json";    memory_vendored="protocol+schema"; }
[ -f "$repo/modules/memory/memory.invariants.yaml" ] && cp "$repo/modules/memory/memory.invariants.yaml" "$out/memory/memory.invariants.yaml"

# --- plugin + runtime + docs ---
cp -R "$here/plugin"    "$out/plugin"
cp "$here/init.sh"      "$out/init.sh"
cp "$here/bootstrap.sh" "$out/bootstrap.sh"
cp -R "$here/ci"        "$out/ci"
cp "$here/Dockerfile"   "$out/Dockerfile"
cp "$here/README.md"    "$out/README.md"
cp "$here/GUIDE.md"     "$out/GUIDE.md"
chmod +x "$out/init.sh" "$out/bootstrap.sh" "$out/cuo/gates/run-gates.sh" 2>/dev/null || true

# make the plugin self-contained: carry the cuo docs so the bundled skill works standalone
mkdir -p "$out/plugin/skills/ship-feature-requests/cuo"
cp "$out/cuo/ship-feature-requests.md" "$out/cuo/EXECUTION-DISCIPLINE.md" "$out/cuo/STATUS-REFERENCE.md" "$out/plugin/skills/ship-feature-requests/cuo/"

# --- profile + manifest ---
profile="reduced"
[ "$vendored_skills" -gt 0 ] && [ "$caf_vendored" = "yes" ] && profile="full"
ver="$(cd "$repo" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
cyver="$(tr -d ' \n\r' < "$repo/VERSION" 2>/dev/null || echo 0.0.0)"
echo "$cyver" > "$out/VERSION"     # plain file so `init --check`/update can compare fast
cat > "$out/manifest.yaml" <<EOF
# Generated by tools/cyberos-init/build.sh - do not edit by hand.
vendor: cyberos
cyberos_version: $cyver     # the single distribution version (module versions are internal)
built_from_commit: $ver
built_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
profile: $profile          # full = skills + caf vendored; reduced = doc-driven + repo's own gates
modules:
  cuo:    { workflow: ship-feature-requests, normative_docs: 3, author_audit_skills: $vendored_skills, caf_tooling: $caf_vendored }
  memory: { protocol: $memory_vendored }
notes: >
  init.sh lays this out under a target repo's gitignored .cyberos/, by module. Doc-driven
  mode always works; missing skills/caf degrade to the reduced-profile floor (the target
  repo's own build/lint/test + coverage + code review + the two human gates).
EOF

echo "cyberos-init: done. profile=$profile skills=$vendored_skills caf=$caf_vendored"
echo "cyberos-init: payload at $out - init.sh lays it out under a target repo's .cyberos/ (gitignored)"
