//! Wasmtime engine + Component-Model invocation for skill WASM components.
//!
//! Compiled behind the `wasm` feature gate so the workspace builds without
//! wasm32-wasi installed. To enable:
//!
//! ```text
//! rustup target add wasm32-wasi
//! cargo build --features wasm
//! ```
//!
//! Architecture (audit §4 / §5 refactored architecture):
//!   - One Engine per host (Wasmtime's docs: Engine is thread-safe, share liberally)
//!   - One AOT-compiled Component per skill, cached at
//!     ~/.cyberos/cache/wasm/<sha256>.cwasm (or $CYBEROS_WASM_CACHE)
//!   - Per-invocation Store with a freshly-built WasiCtx derived from the
//!     skill's `allowed-tools` declaration + operator grants
//!   - JSON in -> JSON out via the cyberos:skill/invocation Component-Model
//!     interface generated by `bindgen!`
//!
//! Phase 5 status: the engine, AOT cache, and capability-translator code
//! compile and unit-test. End-to-end execution requires a real wasm32-wasi
//! component (Phase 5 also adds toolchain/build.ts componentize-js wiring;
//! see ../toolchain/README.md for the full pipeline).

#![cfg(feature = "wasm")]

use anyhow::{Context, Result};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use wasmtime::component::{Component, Linker, ResourceTable, Val};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

use crate::capabilities::Capability;

/// Host state plumbed into every Wasmtime Store.
pub struct HostState {
    pub wasi: WasiCtx,
    pub table: ResourceTable,
    pub skill_name: String,
}

impl WasiView for HostState {
    fn ctx(&mut self) -> &mut WasiCtx { &mut self.wasi }
    fn table(&mut self) -> &mut ResourceTable { &mut self.table }
}

/// Shared engine. One per host process. Cheap to clone via `Arc`.
pub fn make_engine() -> Result<Arc<Engine>> {
    let mut cfg = Config::new();
    cfg.async_support(false);
    cfg.consume_fuel(false);
    cfg.cranelift_opt_level(wasmtime::OptLevel::Speed);
    cfg.wasm_component_model(true);
    // AOT cache directory — disk-persisted, content-addressed by component bytes.
    let cache_dir = wasm_cache_dir()?;
    std::fs::create_dir_all(&cache_dir).ok();
    // (Wasmtime has its own internal cache; we maintain our own AOT artifacts
    // alongside it for explicit content-hash visibility — see compile_aot below.)
    Ok(Arc::new(Engine::new(&cfg)?))
}

pub fn wasm_cache_dir() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("CYBEROS_WASM_CACHE") {
        return Ok(PathBuf::from(p));
    }
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home).join(".cyberos").join("cache").join("wasm"))
}

/// Compute SHA-256 of a file. Used as the AOT cache key.
pub fn content_hash(path: &Path) -> Result<String> {
    let bytes = std::fs::read(path)?;
    let mut h = Sha256::new();
    h.update(&bytes);
    Ok(format!("{:x}", h.finalize()))
}

/// Compile (or reuse cached) AOT artifact for a skill's wasm component.
pub fn compile_aot(engine: &Engine, wasm_path: &Path) -> Result<Component> {
    let hash = content_hash(wasm_path)?;
    let cache_path = wasm_cache_dir()?.join(format!("{}.cwasm", hash));

    if cache_path.is_file() {
        // SAFETY: trusted cache directory under $HOME with content-addressed
        // file names — re-deserialise is safe per wasmtime docs.
        let bytes = std::fs::read(&cache_path)?;
        let component = unsafe { Component::deserialize(engine, &bytes) }?;
        return Ok(component);
    }

    let component = Component::from_file(engine, wasm_path)?;
    let serialised = component.serialize()?;
    if let Some(parent) = cache_path.parent() {
        std::fs::create_dir_all(parent).ok();
    }
    std::fs::write(&cache_path, &serialised)?;
    Ok(component)
}

/// Build a WasiCtx scoped exactly to the operator-granted capabilities.
/// Defaults to ZERO ambient authority (audit §4).
pub fn build_wasi_for_caps(skill_dir: &Path, granted: &[Capability]) -> WasiCtx {
    let mut b = WasiCtxBuilder::new();
    // Inherit stdin/stdout/stderr so the JSON I/O bridge works.
    b.inherit_stdin().inherit_stdout().inherit_stderr();

    for cap in granted {
        match cap.name.as_str() {
            "read_file" | "write_file" => {
                // Preopen the skill's own directory. WASI 0.2 preopens are
                // currently undifferentiated read/write — Phase 6 will narrow
                // this once wasmtime exposes per-preopen permission flags.
                if let Err(e) = b.preopened_dir(
                    skill_dir,
                    ".",
                    wasmtime_wasi::DirPerms::all(),
                    wasmtime_wasi::FilePerms::all(),
                ) {
                    tracing::warn!(
                        skill_dir = %skill_dir.display(),
                        error = %e,
                        "failed to preopen skill dir for {} capability",
                        cap.name
                    );
                }
            }
            // Network is gated by argument-pattern in Capability.argument;
            // wasmtime doesn't have a built-in domain allowlister for WASI 0.2
            // Sockets yet — flag this for Phase 6 GA work.
            "fetch_url" => {
                tracing::warn!(
                    skill_dir = %skill_dir.display(),
                    "fetch_url capability requested — Phase 5 stub: WASI 0.2 sockets domain allowlist pending. Skill will see no network."
                );
            }
            other => {
                tracing::warn!(cap = other, "unknown capability — ignored");
            }
        }
    }
    b.build()
}

/// End-to-end: load skill's wasm, build WASI ctx, instantiate, call invocation/run.
///
/// The cyberos:skill/invocation interface (see crates/host/wit/cyberos-skill.wit)
/// declares a single `run(request) -> response` function. We locate it
/// dynamically through the component-model export tree to avoid the
/// `bindgen!` macro's hard dependency on the generated trait surface,
/// which has shifted between wasmtime minor versions.
pub fn run_component(
    engine: &Engine,
    skill_dir: &Path,
    skill_name: &str,
    granted: &[Capability],
    input_json: &str,
    capability_names: Vec<String>,
) -> Result<String> {
    let wasm_path = skill_dir.join("dist/skill.wasm");
    if !wasm_path.is_file() {
        anyhow::bail!("no dist/skill.wasm at {}", wasm_path.display());
    }
    let component = compile_aot(engine, &wasm_path)?;

    let wasi = build_wasi_for_caps(skill_dir, granted);
    let mut store = Store::new(engine, HostState {
        wasi,
        table: ResourceTable::new(),
        skill_name: skill_name.to_owned(),
    });

    let mut linker: Linker<HostState> = Linker::new(engine);
    wasmtime_wasi::add_to_linker_sync(&mut linker)?;

    // Bind the cyberos:skill/logging.log import — Phase 5 stub routes to
    // tracing::info!. Phase 6 will wire a proper structured-tracing sink.
    let mut logging = linker.instance("cyberos:skill/logging")?;
    logging.func_wrap(
        "log",
        |_store: wasmtime::StoreContextMut<'_, HostState>, (level, message): (String, String)| {
            tracing::info!(level = %level, message = %message, "skill log");
            Ok(())
        },
    )?;

    let instance = linker.instantiate(&mut store, &component)?;

    // Look up the exported `cyberos:skill/invocation` instance and its
    // `run` function. Dynamic lookup keeps us decoupled from bindgen API
    // churn across wasmtime minor versions.
    let invocation_idx = instance
        .get_export(&mut store, None, "cyberos:skill/invocation")
        .context("component does not export cyberos:skill/invocation")?;
    let run_idx = instance
        .get_export(&mut store, Some(&invocation_idx), "run")
        .context("cyberos:skill/invocation does not export `run`")?;
    let run_func = instance
        .get_func(&mut store, run_idx)
        .context("`run` is not a function")?;

    // Build the request record. Component-model records are positional Vals.
    let req_val = Val::Record(vec![
        ("input".to_owned(), Val::String(input_json.to_owned())),
        (
            "capabilities".to_owned(),
            Val::List(
                capability_names
                    .into_iter()
                    .map(Val::String)
                    .collect(),
            ),
        ),
    ]);

    let mut results = vec![Val::Bool(false)];
    run_func
        .call(&mut store, &[req_val], &mut results)
        .context("calling cyberos:skill/invocation.run")?;
    run_func.post_return(&mut store).ok();

    let response = match results.into_iter().next() {
        Some(Val::Record(fields)) => fields,
        other => anyhow::bail!("unexpected response shape: {:?}", other),
    };

    let mut output = String::new();
    let mut error: Option<String> = None;
    for (name, value) in response {
        match (name.as_str(), value) {
            ("output", Val::String(s)) => output = s,
            ("error", Val::Option(Some(boxed))) => {
                if let Val::String(s) = *boxed {
                    error = Some(s);
                }
            }
            ("error", Val::Option(None)) => {}
            _ => {}
        }
    }
    if let Some(err) = error {
        anyhow::bail!("skill returned error: {}", err);
    }
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn engine_constructs() {
        let _engine = make_engine().expect("engine should build");
    }

    #[test]
    fn content_hash_stable() {
        let td = tempfile::TempDir::new().unwrap();
        let p = td.path().join("a.wasm");
        std::fs::write(&p, b"\x00asm\x01\x00\x00\x00").unwrap();
        let h1 = content_hash(&p).unwrap();
        let h2 = content_hash(&p).unwrap();
        assert_eq!(h1, h2);
        assert_eq!(h1.len(), 64);
    }
}
