/**
 * @cyberos/db — Prisma multi-schema helpers + RLS session-var enforcement.
 *
 * Each module owns a Postgres schema named after its module code (lowercase):
 * `auth`, `proj`, `rew`, etc. Modules MUST go through `withTenant()` to
 * acquire a Prisma client; raw `.connect()` is intentionally not exported,
 * which forces the `app.tenant_id` session variable to be set on every
 * request (FR-AUTH-008).
 */

import type { TenantId, RequestContext } from "@cyberos/shared";
import { Errors } from "@cyberos/shared";

/**
 * Run `fn` with a Prisma client whose connection has `app.tenant_id` set to
 * the request's tenant. After `fn` resolves the variable is reset so a
 * pooled connection can't leak tenant state.
 *
 * Implementation note: this stub keeps the contract intact while individual
 * modules wire their own Prisma client (each generated by `prisma generate`
 * under `apps/{module}/prisma/`). The real implementation lives in v0.2.
 */
export async function withTenant<T>(
  ctx: RequestContext,
  _fn: (db: never) => Promise<T>,
): Promise<T> {
  if (!ctx.tenantId) throw Errors.unauthorized("missing tenant context");
  // TODO(v0.2): SET LOCAL app.tenant_id = $1; run fn; RESET app.tenant_id.
  throw new Error("withTenant() — not implemented; wire your module's Prisma client");
}

/** Compose a residency-aware DATABASE_URL from a TenantId. SRS §5.1. */
export function databaseUrlFor(tenantId: TenantId, residency: RequestContext["residency"]): string {
  const base = process.env.DATABASE_URL ?? "postgres://localhost/cyberos";
  // Real impl: route to the residency cluster; for v0.1 we suffix the search_path.
  return `${base}?schema=public&application_name=cyberos.${tenantId}.${residency}`;
}

export type { TenantId };
