#!/usr/bin/env bash
# test_channels.sh — every channel the manifest ADVERTISES must actually work.
#
# Why this exists. manifest.yaml declares 13 delivery channels. A declared channel proves
# nothing until something runs it -- four of them shipped dead because the DECLARATION and
# the IMPLEMENTATION drifted apart and no check compared them. This gate makes that
# comparison mechanical: it parses the channel list from the same build.sh line that writes
# it into the manifest, then proves each one.
#
# Scope. Channels provable on a dev box run here. curl-bootstrap (network), github-action
# (GH runner) and docker (daemon) are asserted in release.yml instead -- see CI_ONLY below,
# which is itself checked so a channel cannot be quietly dropped from both lists.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
pass=0; fail=0
ok()   { pass=$((pass+1)); printf '  ok   %s\n' "$1"; }
bad()  { fail=$((fail+1)); printf '  FAIL %s\n' "$1"; [ $# -gt 1 ] && printf '       %s\n' "$2"; }

# The channel list is the source of truth: parsed from the same build.sh line that
# writes it into the payload manifest. Hard-coding it here would let the two drift —
# the exact bug this file exists to prevent.
chan_line="$(grep -E '^channels: \[' "$root/tools/install/build.sh" | head -1)"
[ -n "$chan_line" ] || { echo "FATAL: no channels: line in build.sh"; exit 1; }
CHANNELS="$(printf '%s' "$chan_line" | sed 's/^channels: \[//; s/\]$//; s/,//g')"

CI_ONLY="curl-bootstrap github-action docker"
is_ci_only() { case " $CI_ONLY " in *" $1 "*) return 0;; *) return 1;; esac; }

echo "channels declared: $CHANNELS"
echo

# ── mcp-server ───────────────────────────────────────────────────────────────
# Assert the tools the manifest ADVERTISES are the tools the server ANSWERS with.
# A grep for the file's existence cannot see a renamed tool; only tools/list can.
mcp="$root/tools/install/mcp/cyberos-mcp.mjs"
if [ -f "$mcp" ] && command -v node >/dev/null 2>&1; then
  node --check "$mcp" 2>/dev/null && ok "mcp-server: parses" || bad "mcp-server: syntax error"
  declared="$(grep -oE 'tools: \[[^]]*\]' "$root/tools/install/build.sh" | head -1 \
              | sed 's/tools: \[//; s/\]//; s/,//g')"
  answered="$(printf '%s\n' \
    '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"gate","version":"1"}}}' \
    '{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}}' \
    | node "$mcp" 2>/dev/null \
    | python3 -c 'import sys,json
for l in sys.stdin:
    l=l.strip()
    if not l: continue
    try: m=json.loads(l)
    except Exception: continue
    if m.get("id")==2:
        print(" ".join(t["name"] for t in m.get("result",{}).get("tools",[])))' 2>/dev/null)"
  miss=""
  for t in $declared; do
    case " $answered " in *" $t "*) ;; *) miss="$miss $t";; esac
  done
  if [ -z "$miss" ] && [ -n "$answered" ]; then
    ok "mcp-server: advertises [$declared] and answers with them"
  else
    bad "mcp-server: manifest advertises tools the server does not answer:$miss" \
        "answered: ${answered:-<nothing>}"
  fi
else
  bad "mcp-server: $mcp missing or node unavailable"
fi

# ── npx-cli ──────────────────────────────────────────────────────────────────
# `cyberos` is the trigger word; verbs come after it. A bin named after a verb
# (cyberos-install) makes `npx cyberos-install --help` nonsense. The npm
# package.json is GENERATED by build.sh, so build.sh is the source of truth --
# checking a checked-in file would check something npm never sees.
cli="$root/tools/install/cli/bin/cli.mjs"
if [ -f "$cli" ]; then
  ok "npx-cli: cli/bin/cli.mjs present"
  node --check "$cli" 2>/dev/null && ok "npx-cli: cli.mjs parses" \
                                  || bad "npx-cli: cli.mjs syntax error"
  grep -q '"name": *"@cyberskill/cyberos"' "$root/tools/install/build.sh" \
    && ok "npx-cli: build.sh publishes the package as '@cyberskill/cyberos'" \
    || bad "npx-cli: build.sh does not set the npm package name to '@cyberskill/cyberos'"
  grep -q '"cyberos": *"cli/bin/cli.mjs"' "$root/tools/install/build.sh" \
    && ok "npx-cli: build.sh maps bin.cyberos -> cli/bin/cli.mjs" \
    || bad "npx-cli: build.sh does not map bin.cyberos to cli/bin/cli.mjs"
  # A bare `npx cyberos` must print help and change nothing on disk.
  out="$(node "$cli" 2>&1 </dev/null | head -4)"
  printf '%s' "$out" | grep -qi "usage\|command\|cyberos" \
    && ok "npx-cli: bare invocation prints help" \
    || bad "npx-cli: bare invocation printed no help" "$out"
  if node "$cli" __definitely_not_a_command__ >/dev/null 2>&1; then
    bad "npx-cli: unknown command exited 0"
  else
    ok "npx-cli: unknown command exits non-zero"
  fi
else
  bad "npx-cli: declared as a channel but $cli does not exist"
fi

# ── claude-plugin ────────────────────────────────────────────────────────────
pj="$root/tools/install/plugin/.claude-plugin/plugin.json"
if [ -f "$pj" ]; then
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$pj" 2>/dev/null \
    && ok "claude-plugin: plugin.json is valid JSON" \
    || bad "claude-plugin: plugin.json is not valid JSON"
else
  bad "claude-plugin: $pj missing"
fi

# ── copy-folder / root-cli / create-scaffold / makefile ──────────────────────
for f in install.sh version.sh uninstall.sh; do
  [ -f "$root/tools/install/$f" ] && ok "copy-folder: $f present" \
                                  || bad "copy-folder: $f missing"
done
[ -f "$root/tools/install/create.sh" ] && ok "create-scaffold: create.sh present" \
                                       || bad "create-scaffold: create.sh missing"


# ── every declared channel is either proved here or explicitly deferred to CI ──
PROVED="copy-folder git-submodule claude-plugin mcp-server mcp-connector npx-cli root-cli template-repo create-scaffold makefile"
for c in $CHANNELS; do
  case " $PROVED " in *" $c "*) continue;; esac
  if is_ci_only "$c"; then
    ok "$c: deferred to release.yml (needs network/daemon/runner)"
  else
    bad "$c: declared in the manifest but proved by NOTHING — not here, not in CI"
  fi
done

echo
echo "channels: pass=$pass fail=$fail"
[ "$fail" -eq 0 ] || exit 1
