#!/usr/bin/env bash
# test_install_hygiene.sh - install.sh hygiene contract:
#   t01  .gitignore = ONE managed block, regenerated in place; legacy scattered entries lifted;
#        operator lines outside the markers survive re-install byte-for-byte.
#   t02  CHANGELOG.md is created exactly once (never clobbered on re-install).
#   t03  auto-migration: root-level flat tasks relocate to <module>/<STEM>/spec.md (module from
#        frontmatter), module-level flat tasks migrate, references rewrite, verify line is clean.
#   t04  payload self-cleanup: <repo>/.cyberos-install removes itself on success; kept with
#        CYBEROS_KEEP_PAYLOAD=1; non-canonical in-repo copies are never removed.
#   t05_hookspath_*  (TASK-IMP-083) step 6b lands the pre-commit hook where core.hooksPath
#        points (git runs hooks from there, not .git/hooks); no-hooksPath repos stay
#        byte/word-identical; uninstall resolves the same dir and owns-outright only on
#        the exact line-2 header (the old head-5 heuristic deleted short foreign hooks).
#   t06_consumer_template_default / t06_platform_keeps_comment / t06_existing_config_untouched
#        (TASK-IMP-088) step 3b config.yaml scaffold: consumer installs carry a LIVE
#        `task_template: task@1` line; the platform repo (marker file) keeps the commented
#        engineering-spec default; an existing config.yaml is never touched (create-once).
#   t07_workflow_gitignore_patterns (TASK-IMP-090) .workflow/.gitignore seed covers
#        *.ship.json AND *.manifest.json; a pre-existing seed (operator lines, even without
#        a trailing newline) gains the manifest pattern exactly once across two installs.
#   t01 extension (TASK-IMP-094): the managed block also covers the shared .agents/skills
#        entries + the /create-tasks pair's .claude/skills counterparts (once each across a
#        double install), and uninstall strips those artifacts (no orphans; rules pointers stay).
#   t08_gates_env_regen_notice (TASK-IMP-095) step 3 prints ONE line naming the .bak and
#        .cyberos/config.yaml when regeneration changed gates.env; identical re-install and
#        fresh install stay silent.
#   t09_nongit_summary_line (TASK-IMP-096) non-git installs get the one-line ship-tasks git
#        requirement + verbatim remedy in the summary (git rev-parse semantics, so a stale
#        .git FILE remnant is still non-git); git installs print nothing new.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"; repo="$(cd "$here/../../.." && pwd)"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "  ok   $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL $1: $2"; }

echo "building scratch payload..."
bash "$repo/tools/install/build.sh" "$TMP/payload" >/dev/null 2>&1 || { echo FATAL build; exit 1; }

mkrepo() { mkdir -p "$1"; (cd "$1" && git init -q . 2>/dev/null || true); }

t01_gitignore_managed_block() {
  local d="$TMP/gi"; mkrepo "$d"
  # operator rules + a pre-existing managed block carrying the OLD marker wording. The
  # shape-match must still find and replace it -- this is the 21-repo duplicate-block bug.
  #
  # DO NOT rewrite the `init` strings below, or the `legacy=` needle, to current wording.
  # They ARE the thing under test: a check that detects stale text has to spell that text.
  # A sweep renamed them once and the test silently stopped testing anything.
  cat > "$d/.gitignore" <<'GI'
node_modules/
*.log

# >>> cyberos (managed block - regenerated by cyberos init; edit outside the markers) >>>
# vendored machine + local BRAIN store + render intermediates (regenerable via init; tenant data)
.cyberos/
# skill symlinks -> .cyberos/plugin/skills (regenerable via init)
.claude/skills/ship-tasks
.grok/skills/ship-tasks
.commandcode/skills/ship-tasks
.codex/skills/ship-tasks
.opencode/skill/ship-tasks
GI
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1     # second run must not duplicate anything
  local blocks legacy cyb ops np un sp
  blocks="$(grep -c '>>> cyberos' "$d/.gitignore")"
  legacy="$(grep -c 'regenerable via init' "$d/.gitignore" || true)"
  cyb="$(grep -cx '\.cyberos/' "$d/.gitignore")"
  ops=1; { grep -qx 'node_modules/' "$d/.gitignore" && grep -qx '\*.log' "$d/.gitignore"; } || ops=0
  # TASK-IMP-094 round-trip: the regenerated block covers the shared .agents/skills entries
  # and the /create-tasks pair's .claude/skills counterparts - exactly once each even after
  # the double install above (the strip half of the round-trip is what keeps it at one).
  np=1
  for sp in .claude/skills/task-author .claude/skills/task-audit \
            .agents/skills/ship-tasks .agents/skills/task-author .agents/skills/task-audit; do
    [ "$(grep -cxF "$sp" "$d/.gitignore")" = 1 ] || np=0
  done
  # ... and uninstall strips the new-path artifacts (no orphans, dirs pruned when emptied)
  # while the tracked rules pointers stay operator surface.
  un=1
  bash "$d/.cyberos/uninstall.sh" "$d" >/dev/null 2>&1 || un=0
  [ "$(grep -c '>>> cyberos' "$d/.gitignore" || true)" = 0 ] || un=0
  for sp in ship-tasks task-author task-audit; do
    { [ ! -e "$d/.agents/skills/$sp" ] && [ ! -L "$d/.agents/skills/$sp" ]; } || un=0
  done
  { [ ! -L "$d/.claude/skills/task-author" ] && [ ! -L "$d/.claude/skills/task-audit" ]; } || un=0
  [ -f "$d/.devin/rules/cyberos.md" ] || un=0
  [ "$blocks" = 1 ] && [ "$legacy" = 0 ] && [ "$cyb" = 1 ] && [ "$ops" = 1 ] && [ "$np" = 1 ] && [ "$un" = 1 ] \
    && ok t01 || fail t01 "blocks=$blocks legacy=$legacy .cyberos-lines=$cyb operator-lines=$ops new-paths=$np uninstall-strip=$un"
}

t02_changelog_once() {
  local d="$TMP/cl"; mkrepo "$d"
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  [ -f "$d/CHANGELOG.md" ] || { fail t02 "no CHANGELOG.md created"; return; }
  echo "OPERATOR-EDIT" >> "$d/CHANGELOG.md"
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  grep -q "OPERATOR-EDIT" "$d/CHANGELOG.md" && [ "$(grep -c '^# Changelog' "$d/CHANGELOG.md")" = 1 ] \
    && ok t02 || fail t02 "clobbered or duplicated on re-install"
}

t03_root_task_migration() {
  local d="$TMP/mig"; mkrepo "$d"
  mkdir -p "$d/docs/tasks/api"
  printf -- '---\nid: TASK-CORE-001\ntitle: Root task\nmodule: widget-core\nstatus: draft\n---\nbody\n' \
    > "$d/docs/tasks/TASK-CORE-001-root-thing.md"
  printf -- '---\nid: TASK-API-001\ntitle: Mod task\nstatus: draft\n---\nbody\n' \
    > "$d/docs/tasks/api/TASK-API-001-mod-thing.md"
  printf -- '# idx\nsee docs/tasks/TASK-CORE-001-root-thing.md and TASK-CORE-001-root-thing.md\n' \
    > "$d/docs/tasks/INDEX.md"
  out="$(bash "$TMP/payload/install.sh" "$d" 2>&1)"
  local all=1
  [ -f "$d/docs/tasks/widget-core/TASK-CORE-001-root-thing/spec.md" ] || { fail t03-root "not relocated by frontmatter module"; all=0; }
  [ -f "$d/docs/tasks/api/TASK-API-001-mod-thing/spec.md" ]           || { fail t03-mod "module-level flat not migrated"; all=0; }
  grep -q "docs/tasks/widget-core/TASK-CORE-001-root-thing/spec.md" "$d/docs/tasks/INDEX.md" \
    && ! grep -q "TASK-CORE-001-root-thing\.md" "$d/docs/tasks/INDEX.md" || { fail t03-refs "references not rewritten"; all=0; }
  grep -q "flat_task_files_remaining=0 task_folders_missing_spec=0" <<<"$out" || { fail t03-verify "verify line not clean"; all=0; }
  if command -v node >/dev/null 2>&1; then
    [ -f "$d/docs/status/index.html" ] && [ -f "$d/docs/status/assets/status.css" ] && [ -f "$d/docs/status/assets/favicon.svg" ] \
      || { fail t03-page "docs/status/ folder incomplete"; all=0; }
    [ ! -f "$d/.cyberos/status.html" ] && [ ! -f "$d/docs/status.html" ] || { fail t03-oldpage "stale pre-folder page not cleaned"; all=0; }
    grep -q "$(basename "$d") status" "$d/docs/status/index.html" || { fail t03-title "page not titled after the repo"; all=0; }
    ! grep -q "CyberOS status" "$d/docs/status/index.html" || { fail t03-brand "page still titled 'CyberOS status'"; all=0; }
    [ -x "$d/.git/hooks/pre-commit" ] && grep -q cyberos-status-hook "$d/.git/hooks/pre-commit" \
      || { fail t03-hook "auto-sync pre-commit hook missing"; all=0; }
  fi
  # idempotent: second run moves nothing
  out2="$(bash "$TMP/payload/install.sh" "$d" 2>&1)"
  grep -q "nothing to do (already folder-per-task)" <<<"$out2" || { fail t03-idem "second run not a no-op"; all=0; }
  [ "$all" -eq 1 ] && ok t03
}

t04_payload_self_cleanup() {
  local all=1
  local d="$TMP/pc"; mkrepo "$d"
  cp -R "$TMP/payload" "$d/.cyberos-install"
  out="$(bash "$d/.cyberos-install/install.sh" "$d" 2>&1)"
  { [ ! -e "$d/.cyberos-install" ] && grep -q "payload: removed .cyberos-install/" <<<"$out"; } || { fail t04-rm "canonical copy not removed"; all=0; }
  local k="$TMP/pk"; mkrepo "$k"
  cp -R "$TMP/payload" "$k/.cyberos-install"
  out="$(CYBEROS_KEEP_PAYLOAD=1 bash "$k/.cyberos-install/install.sh" "$k" 2>&1)"
  { [ -d "$k/.cyberos-install" ] && grep -q "payload: kept .cyberos-install/" <<<"$out"; } || { fail t04-keep "KEEP_PAYLOAD not honored"; all=0; }
  local n="$TMP/nc"; mkrepo "$n"
  cp -R "$TMP/payload" "$n/vendor-payload"
  out="$(bash "$n/vendor-payload/install.sh" "$n" 2>&1)"
  { [ -d "$n/vendor-payload" ] && grep -q "payload: kept vendor-payload/" <<<"$out"; } || { fail t04-noncanon "non-canonical copy was touched"; all=0; }
  [ "$all" -eq 1 ] && ok t04
}

t05_supersede_old_docs() {
  local all=1 d="$TMP/sup"; mkrepo "$d"
  mkdir -p "$d/docs"
  printf '# my roadmap\nQ3 plans here\n'            > "$d/docs/ROADMAP.md"
  printf '# my backlog\n- TASK-A-001 pending row\n'   > "$d/docs/BACKLOG.md"
  printf '# changes\n\n## [0.2.0] - 2026-01-01\n\n- old release\n' > "$d/docs/CHANGELOG.md"
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  # adoption: content preserved in the canonical homes
  grep -q "TASK-A-001 pending row" "$d/docs/tasks/BACKLOG.md" || { fail t05-adopt-bl "docs/BACKLOG.md not adopted"; all=0; }
  grep -q "0.2.0" "$d/CHANGELOG.md" || { fail t05-adopt-cl "docs/CHANGELOG.md not adopted to root"; all=0; }
  if command -v node >/dev/null 2>&1; then
    # the old standalone docs are REMOVED outright - the page replaces them
    [ ! -f "$d/docs/ROADMAP.md" ] && [ ! -f "$d/docs/BACKLOG.md" ] && [ ! -f "$d/docs/CHANGELOG.md" ] \
      || { fail t05-removed "old docs/ROADMAP|BACKLOG|CHANGELOG still present"; all=0; }
    grep -q "v0.2.0" "$d/docs/status/index.html" || { fail t05-page "adopted changelog not on the page"; all=0; }
    # idempotent: re-install keeps them removed and keeps the adopted content
    bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
    [ ! -f "$d/docs/ROADMAP.md" ] || { fail t05-idem "removed doc resurrected on re-install"; all=0; }
    grep -q "TASK-A-001 pending row" "$d/docs/tasks/BACKLOG.md" || { fail t05-idem-bl "adopted backlog lost on re-install"; all=0; }
  fi
  [ "$all" -eq 1 ] && ok t05
}

t06_hook_append_foreign() {
  local all=1 d="$TMP/hk"; mkrepo "$d"
  mkdir -p "$d/.git/hooks"
  printf '#!/bin/sh\necho foreign-lint\nfalse\n' > "$d/.git/hooks/pre-commit"; chmod +x "$d/.git/hooks/pre-commit"
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  grep -q "echo foreign-lint" "$d/.git/hooks/pre-commit" || { fail t06-keep "foreign hook body lost"; all=0; }
  [ "$(grep -c '>>> cyberos-status-hook' "$d/.git/hooks/pre-commit")" = 1 ] || { fail t06-append "marked block not appended exactly once"; all=0; }
  bash "$TMP/payload/install.sh" "$d" >/dev/null 2>&1
  [ "$(grep -c '>>> cyberos-status-hook' "$d/.git/hooks/pre-commit")" = 1 ] || { fail t06-idem "block duplicated on re-install"; all=0; }
  # the appended block runs AFTER the foreign body and must preserve its failing exit code (1)
  ( cd "$d" && sh .git/hooks/pre-commit >/dev/null 2>&1 ); [ "$?" = 1 ] || { fail t06-exit "foreign exit code not preserved"; all=0; }
  [ "$all" -eq 1 ] && ok t06
}

# ---------------------------------------------------------------------------
# t05_hookspath_* - TASK-IMP-083: install/uninstall follow core.hooksPath.
# Hook-focused installs skip everything the hook path under test does not need
# (migrate/memory/MCP) to keep the suite fast; t05_hookspath_standalone leaves
# the page UNRENDERED on purpose so the commit proves the hook itself fired.
# ---------------------------------------------------------------------------
_t05_install() { CYBEROS_NO_MIGRATE=1 CYBEROS_NO_MEMORY=1 CYBEROS_NO_MCP=1 bash "$TMP/payload/install.sh" "$1" 2>&1; }
T05_STANDALONE_OUT=""   # captured by t05_hookspath_standalone; asserted again by t05_summary_names_path

t05_hookspath_standalone() {
  local all=1 d="$TMP/hp-alone"; mkrepo "$d"
  git -C "$d" config core.hooksPath .githooks
  T05_STANDALONE_OUT="$(_t05_install "$d")"
  { [ -f "$d/.githooks/pre-commit" ] && [ -x "$d/.githooks/pre-commit" ]; } \
    || { fail t05_hookspath_standalone "hook missing or not executable at .githooks/pre-commit"; all=0; }
  [ "$(sed -n '2p' "$d/.githooks/pre-commit" 2>/dev/null)" = "# cyberos-status-hook v2 (managed by cyberos install)" ] \
    || { fail t05_hookspath_standalone "standalone v2 header not on line 2"; all=0; }
  [ ! -e "$d/.git/hooks/pre-commit" ] \
    || { fail t05_hookspath_standalone "install also wrote .git/hooks/pre-commit (inert litter)"; all=0; }
  if command -v node >/dev/null 2>&1; then
    # the hook must FIRE from the configured dir: a backlog-touching commit regenerates
    # docs/status/ and stages it into the same commit (install above rendered no page).
    ( cd "$d" && git config user.email t05@test && git config user.name t05 \
      && mkdir -p docs/tasks/m && printf 'x\n' > docs/tasks/m/x.md \
      && git add docs/tasks/m/x.md && git commit -q -m t05 ) >/dev/null 2>&1 \
      || { fail t05_hookspath_standalone "backlog commit failed under the installed hook"; all=0; }
    ( cd "$d" && git ls-tree -r --name-only HEAD 2>/dev/null | grep -q '^docs/status/' ) \
      || { fail t05_hookspath_standalone "hook did not fire from .githooks/ (no docs/status in commit)"; all=0; }
  fi
  [ "$all" -eq 1 ] && ok t05_hookspath_standalone
}

t05_hookspath_foreign_append() {
  local all=1 d="$TMP/hp-foreign"; mkrepo "$d"
  git -C "$d" config core.hooksPath .githooks
  mkdir -p "$d/.githooks"
  # 3 lines, falls through with status 7 (so the appended block itself must re-raise it).
  printf '#!/bin/sh\necho foreign-hp\n(exit 7)\n' > "$d/.githooks/pre-commit"
  chmod +x "$d/.githooks/pre-commit"
  _t05_install "$d" >/dev/null
  [ "$(head -1 "$d/.githooks/pre-commit")" = '#!/bin/sh' ] \
    || { fail t05_hookspath_foreign_append "foreign first line not byte-preserved"; all=0; }
  grep -qx 'echo foreign-hp' "$d/.githooks/pre-commit" \
    || { fail t05_hookspath_foreign_append "foreign body lost"; all=0; }
  { [ "$(grep -c '>>> cyberos-status-hook' "$d/.githooks/pre-commit")" = 1 ] \
    && [ "$(grep -c '<<< cyberos-status-hook' "$d/.githooks/pre-commit")" = 1 ]; } \
    || { fail t05_hookspath_foreign_append "block markers not present exactly once"; all=0; }
  _t05_install "$d" >/dev/null                       # re-entry: state machine must not duplicate
  [ "$(grep -c '>>> cyberos-status-hook' "$d/.githooks/pre-commit")" = 1 ] \
    || { fail t05_hookspath_foreign_append "block duplicated on re-install"; all=0; }
  # nothing staged -> the appended block captures $? from the foreign body and re-raises 7
  ( cd "$d" && sh .githooks/pre-commit >/dev/null 2>&1 ); [ "$?" = 7 ] \
    || { fail t05_hookspath_foreign_append "foreign exit 7 not preserved"; all=0; }
  [ "$all" -eq 1 ] && ok t05_hookspath_foreign_append
}

t05_no_hookspath_regression() {
  local all=1 d="$TMP/hp-none"; mkrepo "$d"
  local out; out="$(_t05_install "$d")"
  [ -x "$d/.git/hooks/pre-commit" ] \
    || { fail t05_no_hookspath_regression "hook not at .git/hooks/pre-commit"; all=0; }
  [ "$(sed -n '2p' "$d/.git/hooks/pre-commit" 2>/dev/null)" = "# cyberos-status-hook v2 (managed by cyberos install)" ] \
    || { fail t05_no_hookspath_regression "standalone v2 header not on line 2"; all=0; }
  # today's auto-sync summary line, fixed-string exact: any inserted " at <path>" breaks this
  grep -qF "auto-sync -> pre-commit hook v2 installed (blocks if docs/status regen fails; auto-stages status page); run-gates.sh also regenerates the page after every gates run" <<<"$out" \
    || { fail t05_no_hookspath_regression "auto-sync summary line drifted from today's wording"; all=0; }
  grep -qi 'hookspath' <<<"$out" \
    && { fail t05_no_hookspath_regression "hooksPath wording leaked into no-hooksPath output"; all=0; }
  grep -qF " at .githooks/pre-commit" <<<"$out" \
    && { fail t05_no_hookspath_regression "path suffix leaked into no-hooksPath summary"; all=0; }
  [ "$all" -eq 1 ] && ok t05_no_hookspath_regression
}

t05_hookspath_uninstall() {
  local all=1 d="$TMP/hp-unin"; mkrepo "$d"
  git -C "$d" config core.hooksPath .githooks
  _t05_install "$d" >/dev/null
  [ -f "$d/.githooks/pre-commit" ] || { fail t05_hookspath_uninstall "precondition: install left no hook"; all=0; }
  bash "$d/.cyberos/uninstall.sh" "$d" >/dev/null 2>&1 \
    || { fail t05_hookspath_uninstall "uninstall exited nonzero"; all=0; }
  [ ! -e "$d/.githooks/pre-commit" ] || { fail t05_hookspath_uninstall "managed hook not removed from .githooks/"; all=0; }
  [ ! -e "$d/.git/hooks/pre-commit" ] || { fail t05_hookspath_uninstall ".git/hooks/pre-commit touched"; all=0; }
  [ "$all" -eq 1 ] && ok t05_hookspath_uninstall
}

t05_short_foreign_uninstall_preserved() {
  # THE head-5 regression: a foreign hook SHORTER than five lines + our appended block puts
  # the `>>>` marker inside `head -5`; uninstall's old `head -5 | grep -q` ownership
  # heuristic classified the file as ours and rm -f'd the user's hook whole. The exact
  # line-2 test must strip only the marked block and keep the foreign bytes.
  local all=1 d="$TMP/hp-short"; mkrepo "$d"
  git -C "$d" config core.hooksPath .githooks
  mkdir -p "$d/.githooks"
  printf '#!/bin/sh\necho keep-me\n(exit 7)\n' > "$d/.githooks/pre-commit"
  chmod +x "$d/.githooks/pre-commit"
  _t05_install "$d" >/dev/null                       # appends the marked block
  grep -q '>>> cyberos-status-hook' "$d/.githooks/pre-commit" \
    || { fail t05_short_foreign_uninstall_preserved "precondition: block not appended"; all=0; }
  # construction check: the marker DOES sit inside head -5, i.e. the OLD heuristic would
  # match (and delete the file). Keeps this scenario honest if the seed hook ever grows.
  head -5 "$d/.githooks/pre-commit" | grep -q 'cyberos-status-hook' \
    || { fail t05_short_foreign_uninstall_preserved "construction broken: marker outside head -5, old bug not exercised"; all=0; }
  bash "$d/.cyberos/uninstall.sh" "$d" >/dev/null 2>&1
  [ -f "$d/.githooks/pre-commit" ] \
    || { fail t05_short_foreign_uninstall_preserved "foreign hook DELETED whole (head-5 heuristic regression)"; return; }
  printf '#!/bin/sh\necho keep-me\n(exit 7)\n' > "$TMP/hp-short.want"
  head -3 "$d/.githooks/pre-commit" | cmp -s - "$TMP/hp-short.want" \
    || { fail t05_short_foreign_uninstall_preserved "foreign body not byte-preserved"; all=0; }
  grep -q 'cyberos-status-hook' "$d/.githooks/pre-commit" \
    && { fail t05_short_foreign_uninstall_preserved "cyberos block remnants left behind"; all=0; }
  ( cd "$d" && sh .githooks/pre-commit >/dev/null 2>&1 ); [ "$?" = 7 ] \
    || { fail t05_short_foreign_uninstall_preserved "stripped hook lost its exit-7 semantics"; all=0; }
  [ "$all" -eq 1 ] && ok t05_short_foreign_uninstall_preserved
}

t05_summary_names_path() {
  # asserts on t05_hookspath_standalone's captured install output (same scenario, one install)
  grep -qF " at .githooks/pre-commit" <<<"$T05_STANDALONE_OUT" \
    && ok t05_summary_names_path \
    || fail t05_summary_names_path "summary does not name .githooks/pre-commit"
}

t05_non_git_skip() {
  local d="$TMP/hp-nogit"; mkdir -p "$d"             # deliberately NO git init
  local out; out="$(_t05_install "$d")"
  grep -qF "skipped (not a git checkout)" <<<"$out" \
    && ok t05_non_git_skip \
    || fail t05_non_git_skip "non-git summary line missing"
}

# ---------------------------------------------------------------------------
# t06_* (TASK-IMP-088) - step 3b config.yaml scaffold. Config scaffolding does not
# depend on migrate/memory/MCP, so these installs use the speed flags like _t05_install.
# ---------------------------------------------------------------------------
_t06_install() { CYBEROS_NO_MIGRATE=1 CYBEROS_NO_MEMORY=1 CYBEROS_NO_MCP=1 bash "$TMP/payload/install.sh" "$1" 2>&1; }

t06_consumer_template_default() {
  local all=1 d="$TMP/ct-consumer"; mkrepo "$d"
  _t06_install "$d" >/dev/null
  [ -f "$d/.cyberos/config.yaml" ] || { fail t06_consumer_template_default "no config.yaml scaffolded"; return; }
  grep -qx 'task_template: task@1' "$d/.cyberos/config.yaml" \
    || { fail t06_consumer_template_default "live task@1 line missing"; all=0; }
  grep -q 'engineering-spec@1' "$d/.cyberos/config.yaml" \
    && { fail t06_consumer_template_default "engineering-spec line present on a consumer install"; all=0; }
  grep -qx '# profile: full' "$d/.cyberos/config.yaml" && grep -qx '# coverage_threshold: 90' "$d/.cyberos/config.yaml" \
    || { fail t06_consumer_template_default "rest of the scaffold not as today"; all=0; }
  [ "$all" -eq 1 ] && ok t06_consumer_template_default
}

t06_platform_keeps_comment() {
  local all=1 d="$TMP/ct-platform"; mkrepo "$d"
  mkdir -p "$d/modules/memory"; : > "$d/modules/memory/memory.schema.json"   # is_platform_repo()'s marker file
  _t06_install "$d" >/dev/null
  [ -f "$d/.cyberos/config.yaml" ] || { fail t06_platform_keeps_comment "no config.yaml scaffolded"; return; }
  grep -qx '# task_template: engineering-spec@1' "$d/.cyberos/config.yaml" \
    || { fail t06_platform_keeps_comment "commented engineering-spec default missing"; all=0; }
  grep -qx 'task_template: task@1' "$d/.cyberos/config.yaml" \
    && { fail t06_platform_keeps_comment "live task@1 line leaked into the platform scaffold"; all=0; }
  [ "$all" -eq 1 ] && ok t06_platform_keeps_comment
}

t06_existing_config_untouched() {
  local d="$TMP/ct-existing"; mkrepo "$d"
  mkdir -p "$d/.cyberos"
  printf '# operator config\ntask_template: engineering-spec@1\ncustom: yes\n' > "$d/.cyberos/config.yaml"
  cp "$d/.cyberos/config.yaml" "$TMP/ct-existing.want"
  _t06_install "$d" >/dev/null                        # re-install over the pre-seeded file
  cmp -s "$d/.cyberos/config.yaml" "$TMP/ct-existing.want" \
    && ok t06_existing_config_untouched \
    || fail t06_existing_config_untouched "pre-seeded config.yaml not byte-identical after re-install"
}

# t07 (TASK-IMP-090) - .workflow/.gitignore covers ship AND author-manifest run state;
# append-once migration for pre-existing seeds. Same speed flags as t06 (the seed is
# written at install step 0, before migrate/memory/MCP).
t07_workflow_gitignore_patterns() {
  local all=1 f="$TMP/wf-fresh"; mkrepo "$f"
  _t06_install "$f" >/dev/null
  local gi="$f/docs/tasks/.workflow/.gitignore"
  [ -f "$gi" ] || { fail t07_workflow_gitignore_patterns "fresh install wrote no .workflow/.gitignore"; return; }
  { grep -qxF '*.ship.json' "$gi" && grep -qxF '*.manifest.json' "$gi"; } \
    || { fail t07_workflow_gitignore_patterns "fresh seed missing a pattern"; all=0; }
  local e="$TMP/wf-exist"; mkrepo "$e"
  mkdir -p "$e/docs/tasks/.workflow"
  printf '*.ship.json\n# operator note\nkeep-me.json' > "$e/docs/tasks/.workflow/.gitignore"   # pre-IMP-090 seed + operator lines, NO trailing newline
  _t06_install "$e" >/dev/null
  _t06_install "$e" >/dev/null                       # append-once must hold across two installs
  local gi2="$e/docs/tasks/.workflow/.gitignore"
  [ "$(grep -cxF '*.manifest.json' "$gi2")" = 1 ] \
    || { fail t07_workflow_gitignore_patterns "manifest pattern not exactly once after two installs"; all=0; }
  [ "$(grep -cxF '*.ship.json' "$gi2")" = 1 ] \
    || { fail t07_workflow_gitignore_patterns "ship pattern churned"; all=0; }
  { grep -qxF '# operator note' "$gi2" && grep -qxF 'keep-me.json' "$gi2"; } \
    || { fail t07_workflow_gitignore_patterns "operator lines lost or mangled (trailing-newline heal broken)"; all=0; }
  [ "$all" -eq 1 ] && ok t07_workflow_gitignore_patterns
}

# t08 (TASK-IMP-095) - gates.env regeneration notice. A prior file that DIFFERS from the
# regenerated one earns exactly one line naming the .bak path and the durable override home;
# an identical re-install and a fresh install stay silent (nothing was lost). Speed flags ok:
# step 3 runs before migrate/memory/MCP.
t08_gates_env_regen_notice() {
  local all=1 d="$TMP/genv"; mkrepo "$d"
  local out line bak
  out="$(_t06_install "$d")"
  grep -q 'gates.env regenerated' <<<"$out" \
    && { fail t08_gates_env_regen_notice "fresh install printed the notice"; all=0; }
  out="$(_t06_install "$d")"
  grep -q 'gates.env regenerated' <<<"$out" \
    && { fail t08_gates_env_regen_notice "unedited re-install printed the notice"; all=0; }
  printf 'OPERATOR_EDIT="kept-out-of-regen"\n' >> "$d/.cyberos/gates.env"
  out="$(_t06_install "$d")"
  line="$(grep 'gates.env regenerated' <<<"$out" || true)"
  if [ -z "$line" ]; then
    fail t08_gates_env_regen_notice "edited re-install printed no notice"; all=0
  else
    [ "$(grep -c 'gates.env regenerated' <<<"$out")" = 1 ] \
      || { fail t08_gates_env_regen_notice "notice printed more than once"; all=0; }
    grep -qF 'durable overrides belong in .cyberos/config.yaml' <<<"$line" \
      || { fail t08_gates_env_regen_notice "notice does not name the durable override home"; all=0; }
    bak="$(sed -n 's/.*previous kept at \(.*\)); durable overrides.*/\1/p' <<<"$line")"
    if [ -n "$bak" ] && [ -f "$bak" ]; then
      grep -qF 'OPERATOR_EDIT="kept-out-of-regen"' "$bak" \
        || { fail t08_gates_env_regen_notice ".bak named by the notice does not carry the operator edit"; all=0; }
    else
      fail t08_gates_env_regen_notice "notice names no existing .bak (got: '$bak')"; all=0
    fi
  fi
  [ "$all" -eq 1 ] && ok t08_gates_env_regen_notice
}

# t09 (TASK-IMP-096) - the summary states the ship-tasks git requirement on non-git targets
# and stays silent on git ones. Non-git detection is git-rev-parse-based (matching install.sh's
# own root resolution), NOT a -d .git probe - a stale .git FILE remnant is still non-git.
# CYBEROS_NO_MIGRATE path per spec 1.3.
t09_nongit_summary_line() {
  local all=1 d="$TMP/nogit-sum"; mkdir -p "$d"      # deliberately NO git init
  local out
  out="$(_t06_install "$d")"
  [ "$(grep -cF 'this repo is not a git checkout - ship-tasks needs one' <<<"$out")" = 1 ] \
    || { fail t09_nongit_summary_line "non-git install did not print the line exactly once"; all=0; }
  grep -qF 'run: git init -b main && git add -A && git commit -m init' <<<"$out" \
    || { fail t09_nongit_summary_line "remedy command not verbatim"; all=0; }
  local st="$TMP/nogit-stale"; mkdir -p "$st"; printf 'gitdir: /nonexistent\n' > "$st/.git"
  out="$(_t06_install "$st")"
  grep -qF 'this repo is not a git checkout' <<<"$out" \
    || { fail t09_nongit_summary_line "stale .git remnant not treated as non-git (rev-parse semantics)"; all=0; }
  local g="$TMP/git-sum"; mkrepo "$g"
  out="$(_t06_install "$g")"
  grep -qF 'this repo is not a git checkout' <<<"$out" \
    && { fail t09_nongit_summary_line "git install printed the non-git line"; all=0; }
  [ "$all" -eq 1 ] && ok t09_nongit_summary_line
}

t01_gitignore_managed_block
t02_changelog_once
t03_root_task_migration
t04_payload_self_cleanup
t05_supersede_old_docs
t06_hook_append_foreign
t05_hookspath_standalone
t05_hookspath_foreign_append
t05_no_hookspath_regression
t05_hookspath_uninstall
t05_short_foreign_uninstall_preserved
t05_summary_names_path
t05_non_git_skip
t06_consumer_template_default
t06_platform_keeps_comment
t06_existing_config_untouched
t07_workflow_gitignore_patterns
t08_gates_env_regen_notice
t09_nongit_summary_line

echo "install-hygiene: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
