#!/usr/bin/env bash
# Fail if the retired feature-request vocabulary reappears in tracked source.
#
# Why this hook exists: the fr->task rename touched 2,500 files and ~32,000 sites.
# Roughly 5,000 lines of vendored skill prose describe the workflow in English, and
# an agent writing new skill text will happily reintroduce "FR" and "feature-request"
# because that is what its context is full of. Without a gate, the old vocabulary
# creeps back in weeks and you end up with both, which is worse than either.
#
# Wired via .githooks/pre-commit (core.hooksPath=.githooks).
#   skip once:  git commit --no-verify
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"

# Deny-list — these legitimately contain the old vocabulary and must never be gated:
#   docs/status/          generated cache; regenerated by the docs-site build
#   tools/caf/field-data/ sanitized external client records (R8); a record may name a real FR
#   docs/tasks/RENAME-EPOCH.md   the id mapping — it IS the old vocabulary, on purpose
#   docs/reviews/task-rename-analysis.md   the analysis doc quotes the old names
#   scripts/migrate_fr_to_task.py          the codemod's own rules
#   modules/memory/tests/test_*            SEALED held-out tests (awh lock)
#   *.png *.jpg ...       binaries produce false regex hits
#
# NARROWED from all of tools/caf/ (2026-07-16). That exemption was justified as "CAF owns
# BACKLOG.md / Task table with unrelated meanings" — true of the word "task", but this PATTERN
# never matches "task". It only matches FR-/feature-request/bare FR, so the blanket exclude
# bought nothing and hid two live prose hits in RETIREMENT.md ("a real FR has passed the
# caf-gate") plus stale pointers to ship-feature-requests.md and docs/feature-requests/.
# With those fixed, the PATTERN scores ZERO hits across tools/caf — so only field-data,
# which is genuinely someone else's record, stays exempt.
EXCLUDE='^(docs/status/|tools/caf/field-data/|docs/tasks/RENAME-EPOCH\.md|docs/reviews/task-rename-analysis\.md|scripts/migrate_fr_to_task\.py|\.pre-commit-hooks/no-legacy-fr-vocabulary\.sh|modules/memory/tests/test_(claude_code_hook|memory_sync|sync_class)\.py)'
BINARY='\.(png|jpg|jpeg|gif|ico|woff2?|ttf|zip|gz|zst|pdf|sqlite|binlog)$'

# R (renamed) belongs in the filter. Without it this gate could not see a rename AT ALL:
# `git mv a b` with no edit reports R100, and ACM silently drops it — so the one operation
# the fr->task epoch most needed policed (git mv != re.sub) was the one it was blind to.
# ACM also means a rename's NEW path never got its contents re-scanned.
staged="$(git diff --cached --name-only --diff-filter=ACMR \
  | grep -Ev "$EXCLUDE" | grep -Ev "$BINARY" || true)"
[ -z "$staged" ] && exit 0

# Three retired shapes:
#   FR-AUTH-111      the id prefix
#   feature-request  the artefact / skill / path name
#   the FR / FRs     the bare abbreviation in prose
PATTERN='\bFR-[A-Z0-9]|feature[-_ ]request|(^|[^A-Za-z0-9_-])FRs?([^A-Za-z0-9_-]|$)'

# QUOTING THE OLD VOCABULARY IS LEGITIMATE — and the reason this exemption exists is
# the first thing this hook ever caught. Two of its three hits on the very first run
# were correct usage:
#
#   STATUS-REFERENCE.md   a blockquote of the retired "Issue Request artefact (TBD)"
#                         spec, kept so the reader can see what it USED to say
#   apply_brain_rename.py a docstring explaining why the BRAIN still holds FR ids
#
# Both must keep the old words to mean anything at all. Excluding those two FILES
# would blind the gate to real regressions inside them, so exempt the LINE SHAPES
# instead — a quote or an explanatory comment, never live prose or code.
#
#   ^\s*>          markdown blockquote          "> Future hook — Issue Request..."
#   ^\s*#          shell / python comment
#   ^\s*//         js / rust comment
#   ^\s*\*         inside a /* */ or docstring continuation
#
# A doc-comment line inside a Python docstring has no marker, so `NOTE:`/`WAS:`/
# `HISTORY:`/`previously` anywhere on the line also exempts it. That is a deliberate
# escape hatch: it must be *typed*, which keeps it a conscious act rather than an
# accident. If you find yourself typing it a lot, the gate is wrong, not you.
# NOTE the `[0-9]+:` prefix in the anchor. `grep -n` emits "42:> quoted text", so an
# anchor of `^[[:space:]]*>` matches nothing — it is looking at the line NUMBER, not
# the line. Same class of bug as everything else this rename turned up: the pattern
# was fine, the thing it was pointed at was not.
QUOTE_SHAPES='^[0-9]+:[[:space:]]*(>|#|//|\*)|NOTE:|WAS:|HISTORY:|previously|retired|legacy'

# PATHS, not just contents. This gate read every staged file's BODY and never once looked at
# its NAME — so `tools/cyberos-install/plugin/skills/ship-feature-requests/SKILL.md` passed clean:
# the codemod had rewritten the contents (name: ship-tasks) but never git mv'd the directory.
# The build then shipped that dir beside an empty plugin/skills/ship-tasks/, and the flagship
# skill could not load in any channel. Contents-not-filenames is the same blind spot this
# rename kept producing; a path is a name too, so check it.
# No exemption shapes here: a path cannot be a quote or an explanatory comment.
path_hits=0
while IFS= read -r f; do
  case "$f" in *feature-request*|*feature_request*) ;; *) continue ;; esac
  if [ "$path_hits" -eq 0 ]; then
    echo "cyberos: retired 'feature-request' vocabulary in a staged PATH." >&2
    echo "         Contents can be renamed by a codemod; a directory needs git mv." >&2
    echo >&2
  fi
  echo "  $f" >&2
  path_hits=$((path_hits + 1))
done <<< "$staged"
if [ "$path_hits" -gt 0 ]; then
  echo >&2
  echo "  git mv <old-path> <new-path>   # then rebuild: bash tools/cyberos-install/build.sh dist/cyberos" >&2
  echo >&2
  exit 1
fi

hits=0
while IFS= read -r f; do
  [ -f "$f" ] || continue
  if out="$(grep -nEI "$PATTERN" "$f" 2>/dev/null | grep -Ev "$QUOTE_SHAPES")"; then
    if [ "$hits" -eq 0 ]; then
      echo "cyberos: retired 'feature-request' vocabulary found in staged files." >&2
      echo "         The atom is a TASK. See docs/tasks/RENAME-EPOCH.md." >&2
      echo >&2
    fi
    echo "  $f" >&2
    echo "$out" | head -3 | sed 's/^/      /' >&2
    hits=$((hits + 1))
  fi
done <<< "$staged"

if [ "$hits" -gt 0 ]; then
  echo >&2
  echo "  FR-AUTH-111      -> TASK-AUTH-111" >&2
  echo "  feature-request  -> task" >&2
  echo "  \"the FR\" / \"FRs\" -> \"the task\" / \"tasks\"" >&2
  echo >&2
  echo "  Intentional? add the path to EXCLUDE in $0, or: git commit --no-verify" >&2
  exit 1
fi
exit 0
