#!/usr/bin/env bash
# Fail if the retired feature-request vocabulary reappears in tracked source.
#
# Why this hook exists: the fr->task rename touched 2,500 files and ~32,000 sites.
# Roughly 5,000 lines of vendored skill prose describe the workflow in English, and
# an agent writing new skill text will happily reintroduce "FR" and "feature-request"
# because that is what its context is full of. Without a gate, the old vocabulary
# creeps back in weeks and you end up with both, which is worse than either.
#
# Wired via .githooks/pre-commit (core.hooksPath=.githooks).
#   skip once:  git commit --no-verify
set -euo pipefail

root="$(git rev-parse --show-toplevel)"
cd "$root"

# Deny-list — these legitimately contain the old vocabulary and must never be gated:
#   docs/status/          generated cache; regenerated by the docs-site build
#   tools/caf/            CAF owns "BACKLOG.md"/"Task table" with unrelated meanings
#   docs/tasks/RENAME-EPOCH.md   the id mapping — it IS the old vocabulary, on purpose
#   docs/reviews/task-rename-analysis.md   the analysis doc quotes the old names
#   scripts/migrate_fr_to_task.py          the codemod's own rules
#   modules/memory/tests/test_*            SEALED held-out tests (awh lock)
#   *.png *.jpg ...       binaries produce false regex hits
EXCLUDE='^(docs/status/|tools/caf/|docs/tasks/RENAME-EPOCH\.md|docs/reviews/task-rename-analysis\.md|scripts/migrate_fr_to_task\.py|\.pre-commit-hooks/no-legacy-fr-vocabulary\.sh|modules/memory/tests/test_(claude_code_hook|memory_sync|sync_class)\.py)'
BINARY='\.(png|jpg|jpeg|gif|ico|woff2?|ttf|zip|gz|zst|pdf|sqlite|binlog)$'

staged="$(git diff --cached --name-only --diff-filter=ACM \
  | grep -Ev "$EXCLUDE" | grep -Ev "$BINARY" || true)"
[ -z "$staged" ] && exit 0

# Three retired shapes:
#   FR-AUTH-111      the id prefix
#   feature-request  the artefact / skill / path name
#   the FR / FRs     the bare abbreviation in prose
PATTERN='\bFR-[A-Z0-9]|feature[-_ ]request|(^|[^A-Za-z0-9_-])FRs?([^A-Za-z0-9_-]|$)'

# QUOTING THE OLD VOCABULARY IS LEGITIMATE — and the reason this exemption exists is
# the first thing this hook ever caught. Two of its three hits on the very first run
# were correct usage:
#
#   STATUS-REFERENCE.md   a blockquote of the retired "Issue Request artefact (TBD)"
#                         spec, kept so the reader can see what it USED to say
#   apply_brain_rename.py a docstring explaining why the BRAIN still holds FR ids
#
# Both must keep the old words to mean anything at all. Excluding those two FILES
# would blind the gate to real regressions inside them, so exempt the LINE SHAPES
# instead — a quote or an explanatory comment, never live prose or code.
#
#   ^\s*>          markdown blockquote          "> Future hook — Issue Request..."
#   ^\s*#          shell / python comment
#   ^\s*//         js / rust comment
#   ^\s*\*         inside a /* */ or docstring continuation
#
# A doc-comment line inside a Python docstring has no marker, so `NOTE:`/`WAS:`/
# `HISTORY:`/`previously` anywhere on the line also exempts it. That is a deliberate
# escape hatch: it must be *typed*, which keeps it a conscious act rather than an
# accident. If you find yourself typing it a lot, the gate is wrong, not you.
# NOTE the `[0-9]+:` prefix in the anchor. `grep -n` emits "42:> quoted text", so an
# anchor of `^[[:space:]]*>` matches nothing — it is looking at the line NUMBER, not
# the line. Same class of bug as everything else this rename turned up: the pattern
# was fine, the thing it was pointed at was not.
QUOTE_SHAPES='^[0-9]+:[[:space:]]*(>|#|//|\*)|NOTE:|WAS:|HISTORY:|previously|retired|legacy'

hits=0
while IFS= read -r f; do
  [ -f "$f" ] || continue
  if out="$(grep -nEI "$PATTERN" "$f" 2>/dev/null | grep -Ev "$QUOTE_SHAPES")"; then
    if [ "$hits" -eq 0 ]; then
      echo "cyberos: retired 'feature-request' vocabulary found in staged files." >&2
      echo "         The atom is a TASK. See docs/tasks/RENAME-EPOCH.md." >&2
      echo >&2
    fi
    echo "  $f" >&2
    echo "$out" | head -3 | sed 's/^/      /' >&2
    hits=$((hits + 1))
  fi
done <<< "$staged"

if [ "$hits" -gt 0 ]; then
  echo >&2
  echo "  FR-AUTH-111      -> TASK-AUTH-111" >&2
  echo "  feature-request  -> task" >&2
  echo "  \"the FR\" / \"FRs\" -> \"the task\" / \"tasks\"" >&2
  echo >&2
  echo "  Intentional? add the path to EXCLUDE in $0, or: git commit --no-verify" >&2
  exit 1
fi
exit 0
