//! Attachment byte storage (richer-messages cluster). Metadata always lives in `chat_attachments`; this
//! module decides where the PAYLOAD lives. Two backends today:
//!
//! - `db` - the original slice-3 behavior (bytea column) and the default, so a bare deploy keeps working.
//! - `fs` - a directory (in production a compose volume on the VPS), which removes the blob weight from
//!   Postgres and makes a much larger per-file cap practical.
//!
//! The enum is the seam where an S3-compatible backend (Vultr Object Storage / R2 / MinIO) lands later as a
//! third variant plus env config - nothing outside this module knows where bytes live. Keys are
//! `<tenant>/<attachment-id>`, so fs paths never contain user-supplied names.

use std::path::{Path, PathBuf};

use uuid::Uuid;

#[derive(Clone, Debug)]
pub enum AttachmentStore {
    /// Bytes in the `chat_attachments.data` column (`storage = 'db'`).
    Db,
    /// Bytes under `root/<tenant>/<id>` (`storage = 'fs'`, `storage_key` = the relative key).
    Fs { root: PathBuf },
}

/// Attachment limits + backend, read once at boot and shared via `AppState`.
#[derive(Clone, Debug)]
pub struct AttachmentConfig {
    pub store: AttachmentStore,
    /// Per-file byte cap, enforced on every upload path (and mirrored to clients via GET /v1/chat/config).
    pub max_bytes: usize,
    /// Max attachments on one message.
    pub max_files: usize,
}

/// The historical slice-3 cap; still the default so a config-less deploy behaves exactly as before.
pub const DEFAULT_MAX_BYTES: usize = 5 * 1024 * 1024;
pub const DEFAULT_MAX_FILES: usize = 10;

impl AttachmentConfig {
    /// CHAT_ATTACHMENT_STORE=db|fs (default db), CHAT_ATTACHMENT_FS_DIR (required for fs; created at boot),
    /// CHAT_ATTACHMENT_MAX_BYTES (default 5 MiB), CHAT_ATTACHMENT_MAX_FILES (default 10). Empty values are
    /// treated as unset, matching how the rest of the service reads env.
    pub fn from_env() -> anyhow::Result<Self> {
        let env = |k: &str| std::env::var(k).ok().filter(|v| !v.trim().is_empty());
        let store = match env("CHAT_ATTACHMENT_STORE").as_deref() {
            None | Some("db") => AttachmentStore::Db,
            Some("fs") => {
                let root = env("CHAT_ATTACHMENT_FS_DIR").ok_or_else(|| {
                    anyhow::anyhow!("CHAT_ATTACHMENT_STORE=fs requires CHAT_ATTACHMENT_FS_DIR")
                })?;
                let root = PathBuf::from(root);
                std::fs::create_dir_all(&root).map_err(|e| {
                    anyhow::anyhow!("create CHAT_ATTACHMENT_FS_DIR {}: {e}", root.display())
                })?;
                AttachmentStore::Fs { root }
            }
            Some(other) => anyhow::bail!("unknown CHAT_ATTACHMENT_STORE '{other}' (db|fs)"),
        };
        let max_bytes = match env("CHAT_ATTACHMENT_MAX_BYTES") {
            Some(v) => v
                .parse::<usize>()
                .map_err(|_| anyhow::anyhow!("CHAT_ATTACHMENT_MAX_BYTES must be an integer"))?,
            None => DEFAULT_MAX_BYTES,
        };
        let max_files = match env("CHAT_ATTACHMENT_MAX_FILES") {
            Some(v) => v
                .parse::<usize>()
                .map_err(|_| anyhow::anyhow!("CHAT_ATTACHMENT_MAX_FILES must be an integer"))?
                .clamp(1, 25),
            None => DEFAULT_MAX_FILES,
        };
        Ok(Self {
            store,
            max_bytes,
            max_files,
        })
    }
}

impl Default for AttachmentConfig {
    /// The pre-cluster behavior: db backend, 5 MiB, up to 10 files. Used by tests.
    fn default() -> Self {
        Self {
            store: AttachmentStore::Db,
            max_bytes: DEFAULT_MAX_BYTES,
            max_files: DEFAULT_MAX_FILES,
        }
    }
}

fn key_path(root: &Path, key: &str) -> PathBuf {
    // Keys are generated by us (`<tenant-uuid>/<attachment-uuid>`), never user input; still, refuse anything
    // that is not two uuid-shaped segments so a corrupted DB row cannot traverse the filesystem.
    root.join(key)
}

/// True when `key` has exactly the `<uuid>/<uuid>` shape this module generates.
pub fn key_is_sane(key: &str) -> bool {
    let mut parts = key.split('/');
    match (parts.next(), parts.next(), parts.next()) {
        (Some(a), Some(b), None) => Uuid::parse_str(a).is_ok() && Uuid::parse_str(b).is_ok(),
        _ => false,
    }
}

impl AttachmentStore {
    /// The value stored in `chat_attachments.storage` for rows this backend writes.
    pub fn kind(&self) -> &'static str {
        match self {
            AttachmentStore::Db => "db",
            AttachmentStore::Fs { .. } => "fs",
        }
    }

    /// Persist the payload for a new attachment. Returns the `storage_key` to record (None for db, where the
    /// bytes go into the row itself).
    pub async fn put(
        &self,
        tenant: Uuid,
        id: Uuid,
        bytes: &[u8],
    ) -> anyhow::Result<Option<String>> {
        match self {
            AttachmentStore::Db => Ok(None),
            AttachmentStore::Fs { root } => {
                let key = format!("{tenant}/{id}");
                let path = key_path(root, &key);
                if let Some(dir) = path.parent() {
                    tokio::fs::create_dir_all(dir).await?;
                }
                // Write-then-rename so a crashed upload never leaves a half-written file under the real key.
                let tmp = path.with_extension("part");
                tokio::fs::write(&tmp, bytes).await?;
                tokio::fs::rename(&tmp, &path).await?;
                Ok(Some(key))
            }
        }
    }

    /// Read a payload back by its `storage_key` (fs only; db rows carry their bytes in the query).
    pub async fn get(&self, key: &str) -> anyhow::Result<Vec<u8>> {
        match self {
            AttachmentStore::Db => anyhow::bail!("db-backed attachment has no storage key"),
            AttachmentStore::Fs { root } => {
                if !key_is_sane(key) {
                    anyhow::bail!("malformed storage key");
                }
                Ok(tokio::fs::read(key_path(root, key)).await?)
            }
        }
    }

    /// Best-effort payload removal (called after a message hard-purges its attachments). A miss is fine.
    pub async fn delete(&self, key: &str) {
        if let AttachmentStore::Fs { root } = self {
            if key_is_sane(key) {
                let _ = tokio::fs::remove_file(key_path(root, key)).await;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn key_sanity() {
        let t = Uuid::from_bytes([7; 16]);
        let a = Uuid::from_bytes([9; 16]);
        assert!(key_is_sane(&format!("{t}/{a}")));
        assert!(!key_is_sane("../../etc/passwd"));
        assert!(!key_is_sane("a/b"));
        assert!(!key_is_sane(&format!("{t}/{a}/x")));
        assert!(!key_is_sane(""));
    }

    #[tokio::test]
    async fn fs_roundtrip_put_get_delete() {
        let dir = std::env::temp_dir().join(format!("chat-att-test-{}", Uuid::new_v4()));
        let store = AttachmentStore::Fs { root: dir.clone() };
        let tenant = Uuid::new_v4();
        let id = Uuid::new_v4();
        let key = store
            .put(tenant, id, b"hello bytes")
            .await
            .expect("put")
            .expect("fs put returns a key");
        assert_eq!(key, format!("{tenant}/{id}"));
        let back = store.get(&key).await.expect("get");
        assert_eq!(back, b"hello bytes");
        store.delete(&key).await;
        assert!(
            store.get(&key).await.is_err(),
            "deleted key no longer reads"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn config_default_matches_slice3() {
        let c = AttachmentConfig::default();
        assert_eq!(c.max_bytes, 5 * 1024 * 1024);
        assert!(matches!(c.store, AttachmentStore::Db));
    }
}
