#!/usr/bin/env python3
"""
migrate_fr_to_task.py — one-wave codemod: feature-request -> task, task -> subtask.

Decisions this script implements (see docs/reviews/task-rename-analysis.md §9):
  D1  the existing task@1 contract (unit of work INSIDE an FR) becomes subtask@1
  D2  all 563 FR IDs are rewritten: FR-<MOD>-<NNN> -> TASK-<MOD>-<NNN>
  D3  archives and audit evidence are rewritten too (pre-1.0, no external consumers)
  D4  one wave

The BRAIN store (.cyberos/memory/store/) is DENIED. It is not a style choice:
the audit ledger is a hash chain (AGENTS.md §6.3) with 252k rows, and every
memory file body's SHA-256 is recorded in a ledger row (§5.3). A byte-level sed
over the store breaks the chain and flips the store to FROZEN. The rename must
be expressed there as move(src,dst)+put(dst,body) through the canonical writer.
See --emit-brain-ops.

Usage:
    python3 scripts/migrate_fr_to_task.py                 # dry run, summary only
    python3 scripts/migrate_fr_to_task.py --show-files    # dry run, list files per rule
    python3 scripts/migrate_fr_to_task.py --apply         # rewrite contents + git mv paths
    python3 scripts/migrate_fr_to_task.py --verify        # assert zero residue post-apply
    python3 scripts/migrate_fr_to_task.py --emit-brain-ops > brain-rename.ndjson
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Deny-list — paths the codemod must never touch.
# CI asserts zero diff under every one of these after --apply.
# ─────────────────────────────────────────────────────────────────────────────
DENY_PREFIXES = (
    ".cyberos/",            # BRAIN store (hash chain, protocol-immutable) + regenerated payload
    "tools/caf/",           # CAF owns "BACKLOG.md" and "Task table" with unrelated meanings;
                            # 63 golden eval fixtures would be corrupted by a blind rewrite
    "dist/",                # build output, regenerated by tools/cyberos-init/build.sh
    ".vercel-out/",         # deploy output
    "docs/status/data/",    # 507 generated per-FR data files, regenerated by the docs-site build
    ".ruff_cache/",
    ".git/",
    "node_modules/",
    "scripts/migrate_fr_to_task.py",   # this file
)

# Binary / non-text extensions we never rewrite.
SKIP_SUFFIXES = (
    ".png", ".jpg", ".jpeg", ".svg", ".ico", ".woff", ".woff2", ".ttf",
    ".zip", ".gz", ".zst", ".binlog", ".sqlite", ".lock", ".pdf",
)

# ─────────────────────────────────────────────────────────────────────────────
# Content rules, applied IN ORDER. Longest / most-specific identifiers first so
# a short pattern cannot eat a long one.
#
# Ordering note: pass 1 frees the word `task` by moving the existing task@1
# contract to subtask@1. Only after that does pass 5 introduce `task@1` as the
# new name for feature_request@1. Running these out of order silently collapses
# the two contracts into one.
#
# Word-boundary note: \btask\b does NOT match inside "subtask" or "sub_tasks"
# (b/t and _/t are both word characters, so there is no boundary). That is what
# makes the subtask-first ordering safe.
# ─────────────────────────────────────────────────────────────────────────────
RULES: list[tuple[str, str, str]] = [
    # ── Pass 1: free the word. The existing task@1 becomes subtask@1. ────────
    ("free-word:contract-literal",   r"\btask@1\b",                    "subtask@1"),
    ("free-word:contract-id",        r"^contract_id: task$",           "contract_id: subtask"),
    ("free-word:contract-path",      r"contracts/task\b",              "contracts/subtask"),
    ("free-word:runner-module",      r"\bfr_with_tasks\b",             "task_with_subtasks"),
    ("free-word:runner-skill-id",    r"\bfr-with-tasks\b",             "task-with-subtasks"),
    ("free-word:runner-class",       r"\bFrWithTasksRunner\b",         "TaskWithSubtasksRunner"),
    ("free-word:frontmatter-field",  r"\bsub_tasks\b",                 "subtasks"),
    # subtask id sub-format: FR-007-T-03 -> TASK-007-S-03 (the -T- infix would
    # read as "task" inside a TASK- id; -S- is unambiguous).
    ("free-word:subtask-id",         r"\bFR-(\d+)-T-(\d{2})\b",        r"TASK-\1-S-\2"),

    # ── Pass 2: FR IDs. D2 = full rewrite. ──────────────────────────────────
    ("id:fr-module-num",             r"\bFR-([A-Z]{2,10})-(\d{3,4})\b", r"TASK-\1-\2"),
    # lowercase form appears in generated filenames (impl-plan-fr-mcp-003.md)
    ("id:fr-module-num-lower",       r"\bfr-([a-z]{2,10})-(\d{3,4})\b", r"task-\1-\2"),

    # ── Pass 3: artefact + skill + command identifiers. ──────────────────────
    ("artefact:feature-request-1",   r"\bfeature_request@1\b",         "task@1"),
    ("artefact:fr-manifest",         r"\bfr-manifest@2\b",             "task-manifest@1"),
    ("skill:fr-author",              r"\bfeature-request-author\b",    "task-author"),
    ("skill:fr-audit",               r"\bfeature-request-audit\b",     "task-audit"),
    ("cmd:ship",                     r"\bship-feature-requests\b",     "ship-tasks"),
    ("cmd:create",                   r"\bcreate-feature-requests\b",   "create-tasks"),

    # ── Pass 4: paths. Must run AFTER the skill/command rules above, because
    #     "docs/feature-requests/" and "contracts/feature-request/" share a stem
    #     with the skill names. ─────────────────────────────────────────────────
    ("path:docs-dir",                r"docs/feature-requests\b",       "docs/tasks"),
    ("path:contract-dir",            r"contracts/feature-request\b",   "contracts/task"),

    # ── Pass 5: frontmatter fields carrying FR IDs. ──────────────────────────
    ("field:related-frs",            r"\brelated_frs\b",               "related_tasks"),

    # ── Pass 5b: code identifiers. D5 = task_id, module-scoped.
    #     Safe at the rename site: `fr_id` appears only in modules/cuo,
    #     modules/skill, scripts/ and tools/ — never in services/mcp-gateway
    #     (which owns mcp_tasks.task_id) or tools/awh (eval task_id). The
    #     overload is repo-wide and semantic, not a shadowing bug. It is
    #     recorded in an ADR and enforced by check_sep986_naming.sh. ─────────
    ("ident:fr-id",                  r"\bfr_id\b",                     "task_id"),
    ("ident:fr-row",                 r"\bfr_row\b",                    "task_row"),
    ("ident:FrRow",                  r"\bFrRow\b",                     "TaskRow"),
    ("ident:FR_ROW_RE",              r"\b_FR_ROW_RE\b",                "_TASK_ROW_RE"),
    ("ident:FR_ID_RE",               r"\b_FR_ID_RE\b",                 "_TASK_ID_RE"),
    ("ident:frs-var",                r"\bfrs\b(?=\s*[:=\)\],])",       "tasks"),

    # ── Pass 6: remaining identifiers, then prose. ───────────────────────────
    ("ident:feature-request-snake",  r"\bfeature_request\b",           "task"),
    ("ident:feature-request-kebab",  r"\bfeature-request\b",           "task"),
    ("ident:feature-requests-kebab", r"\bfeature-requests\b",          "tasks"),
    ("prose:Feature-Requests",       r"\bFeature Requests\b",          "Tasks"),
    ("prose:Feature-Request",        r"\bFeature Request\b",           "Task"),
    ("prose:feature-requests",       r"\bfeature requests\b",          "tasks"),
    ("prose:feature-request",        r"\bfeature request\b",           "task"),
]

# The bare `FR` abbreviation is NOT in RULES. It is 2 characters and appears
# inside unrelated words, inside the FR-<MOD>-<NNN> ids handled above, and in
# third-party prose. --residue reports every remaining site for a human pass.
RESIDUE_PATTERNS = [
    ("bare-FR-abbrev",  re.compile(r"(?<![A-Za-z0-9_-])FRs?(?![A-Za-z0-9_-])")),
    ("fr-lowercase",    re.compile(r"\bfr_id\b|\bfr_row\b|\bFrRow\b|\b_FR_ROW_RE\b|\b_FR_ID_RE\b")),
    ("leftover",        re.compile(r"(?i)feature[-_ ]request")),
]

# Path renames (git mv). Applied after content rewrite.
PATH_RENAMES = [
    ("docs/feature-requests",                    "docs/tasks"),
    ("modules/skill/contracts/task",             "modules/skill/contracts/subtask"),
    ("modules/skill/contracts/feature-request",  "modules/skill/contracts/task"),
    ("modules/skill/feature-request-author",     "modules/skill/task-author"),
    ("modules/skill/feature-request-audit",      "modules/skill/task-audit"),
    ("modules/skill/runners/fr_with_tasks.py",   "modules/skill/runners/task_with_subtasks.py"),
    ("modules/cuo/chief-technology-officer/workflows/ship-feature-requests.md",
     "modules/cuo/chief-technology-officer/workflows/ship-tasks.md"),
    ("tools/cyberos-init/plugin/commands/create-feature-requests.md",
     "tools/cyberos-init/plugin/commands/create-tasks.md"),
    ("scripts/migrate_fr_layout.py",             "scripts/migrate_task_layout.py"),
    ("scripts/repair_fr_yaml.py",                "scripts/repair_task_yaml.py"),
    ("scripts/rebaseline_fr_status.py",          "scripts/rebaseline_task_status.py"),
    ("scripts/awh_goldenset_from_fr.py",         "scripts/awh_goldenset_from_task.py"),
    ("tools/cyberos-init/lib/fr-migrate.sh",     "tools/cyberos-init/lib/task-migrate.sh"),
    ("tools/docs-site/render-fr-catalog.mjs",    "tools/docs-site/render-task-catalog.mjs"),
    ("tools/docs-site/render-fr-pages.mjs",      "tools/docs-site/render-task-pages.mjs"),
]

COMPILED = [(name, re.compile(pat, re.MULTILINE), rep) for name, pat, rep in RULES]


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return Path(out.stdout.strip())


def tracked_files(root: Path) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=root, capture_output=True, text=True, check=True,
    )
    return [p for p in out.stdout.split("\0") if p]


def in_scope(rel: str) -> bool:
    if any(rel.startswith(p) for p in DENY_PREFIXES):
        return False
    if any(rel.endswith(s) for s in SKIP_SUFFIXES):
        return False
    return True


def rewrite(text: str) -> tuple[str, Counter]:
    hits: Counter = Counter()
    for name, pat, rep in COMPILED:
        text, n = pat.subn(rep, text)
        if n:
            hits[name] += n
    return text, hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write changes and git mv paths")
    ap.add_argument("--show-files", action="store_true", help="list files touched per rule")
    ap.add_argument("--verify", action="store_true", help="assert zero residue; exit 1 if any")
    ap.add_argument("--residue", action="store_true", help="report sites the rules cannot reach")
    ap.add_argument("--emit-brain-ops", action="store_true",
                    help="emit NDJSON move/put ops for the BRAIN store (do not sed it)")
    args = ap.parse_args()

    root = repo_root()
    files = [f for f in tracked_files(root) if in_scope(f)]

    if args.emit_brain_ops:
        return emit_brain_ops(root)

    # ── Guard 1: refuse to apply to a dirty tree. ───────────────────────────
    # `git checkout -- .` must be a valid, complete undo. If the tree already
    # has uncommitted work, a failed apply cannot be cleanly reverted.
    if args.apply:
        dirty = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=root, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if dirty:
            print("REFUSING TO APPLY: working tree is dirty.", file=sys.stderr)
            print("Commit or stash first, so `git checkout -- .` is a clean undo.\n",
                  file=sys.stderr)
            print(dirty, file=sys.stderr)
            return 2

    total: Counter = Counter()
    touched: dict[str, list[str]] = {}
    residue: Counter = Counter()
    residue_files: dict[str, set[str]] = {}
    plan: list[tuple[Path, str]] = []   # (path, new_content) — nothing is written yet

    # ── Phase 1: plan every edit in memory. Write nothing. ──────────────────
    for rel in files:
        path = root / rel
        try:
            src = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError):
            continue

        new, hits = rewrite(src)

        if args.residue or args.verify:
            probe = src if args.verify else new
            for rname, rpat in RESIDUE_PATTERNS:
                n = len(rpat.findall(probe))
                if n:
                    residue[rname] += n
                    residue_files.setdefault(rname, set()).add(rel)

        if hits:
            total.update(hits)
            for k in hits:
                touched.setdefault(k, []).append(rel)
            plan.append((path, new))

    changed_files = len(plan)

    # ── Guard 2: pre-flight writability. Abort BEFORE the first write. ──────
    # A crash halfway through leaves a half-renamed repo, which is far worse
    # than not starting. Learned the hard way: an ACL-restricted file killed
    # the first run at file ~1349 of 2498.
    if args.apply:
        unwritable = [p for p, _ in plan if not p.parent.is_dir() or (
            p.exists() and not __import__("os").access(p, __import__("os").W_OK))]
        if unwritable:
            print(f"REFUSING TO APPLY: {len(unwritable)} planned files are not writable.",
                  file=sys.stderr)
            for p in unwritable[:20]:
                print(f"  {p.relative_to(root)}", file=sys.stderr)
            return 2

    # ── Phase 2: commit the plan to disk. ───────────────────────────────────
    if args.apply:
        for path, new in plan:
            path.write_text(new, encoding="utf-8")

    mode = "APPLY" if args.apply else ("VERIFY" if args.verify else "DRY RUN")
    print(f"=== migrate_fr_to_task — {mode} ===")
    print(f"in-scope tracked files : {len(files)}")
    print(f"files with edits       : {changed_files}")
    print(f"total substitutions    : {sum(total.values())}\n")

    print(f"{'rule':32} {'hits':>7}  files")
    for name, _p, _r in RULES:
        n = total.get(name, 0)
        if n:
            print(f"{name:32} {n:7}  {len(touched.get(name, []))}")
            if args.show_files:
                for f in sorted(touched[name])[:12]:
                    print(f"{'':34}   {f}")
                extra = len(touched[name]) - 12
                if extra > 0:
                    print(f"{'':34}   ... +{extra} more")

    if args.residue or args.verify:
        print(f"\n--- residue (needs a human pass) ---")
        if not residue:
            print("none")
        for rname, n in residue.most_common():
            print(f"{rname:32} {n:7}  {len(residue_files[rname])} files")
            if args.show_files:
                for f in sorted(residue_files[rname])[:10]:
                    print(f"{'':34}   {f}")

    if args.apply:
        print("\n--- path renames (git mv) ---")
        for src, dst in PATH_RENAMES:
            s, d = root / src, root / dst
            if not s.exists():
                print(f"skip (absent)  {src}")
                continue
            d.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(["git", "mv", src, dst], cwd=root, check=True)
            print(f"moved          {src} -> {dst}")

        # ── The 563 per-spec directories: docs/tasks/<mod>/FR-MOD-NNN-slug/ ──
        print("\n--- spec directory renames (FR-* -> TASK-*) ---")
        tasks_root = root / "docs" / "tasks"
        moved = 0
        if tasks_root.is_dir():
            # Deepest-first so a parent rename cannot invalidate a child path.
            cands = sorted(
                (p for p in tasks_root.rglob("*") if p.is_dir() and p.name.startswith("FR-")),
                key=lambda p: len(p.parts), reverse=True,
            )
            for p in cands:
                new_name = re.sub(r"^FR-", "TASK-", p.name)
                subprocess.run(
                    ["git", "mv", str(p.relative_to(root)),
                     str((p.parent / new_name).relative_to(root))],
                    cwd=root, check=True,
                )
                moved += 1
        print(f"renamed {moved} spec directories")

        print("\n--- next, by hand ---")
        print("  1. the 13 agent-config files (.cursorrules, .windsurfrules, .grok/GROK.md,")
        print("     .github/copilot-instructions.md, .agents/rules/, .cursor/rules/, AGENTS.md,")
        print("     CLAUDE.md, GEMINI.md, .gitignore managed block, .githooks/pre-commit)")
        print("  2. the bare-FR prose pass (see --residue; 2-char token, needs review)")
        print("  3. .git-blame-ignore-revs <- sha of this commit")
        print("  4. --emit-brain-ops | python3 -m cyberos.writer apply   (never sed the store)")

    if args.verify and residue:
        print("\nVERIFY FAILED: residue remains.")
        return 1
    return 0


def emit_brain_ops(root: Path) -> int:
    """The BRAIN store cannot be sed'd. Emit protocol-legal move+put ops instead.

    Every memory file body's SHA-256 is recorded in an audit row (AGENTS.md §5.3),
    and the ledger is a hash chain (§6.3). Editing a body in place makes the
    recorded content_sha256 wrong and flips the store to FROZEN_RECOVERABLE.
    The protocol-legal expression of a rename is a new move() followed by a new
    put() — the chain then records the rename rather than being invalidated by it.
    """
    store = root / ".cyberos" / "memory" / "store"
    if not store.is_dir():
        print("no BRAIN store at .cyberos/memory/store", file=sys.stderr)
        return 2

    fr_id = re.compile(r"(?i)\bfr-([a-z]{2,10})-(\d{3,4})\b")
    ops = 0
    for p in sorted(store.rglob("*.md")):
        rel = p.relative_to(store).as_posix()
        if rel.startswith(("audit/", "exports/", "index/")):
            continue
        body = p.read_text(encoding="utf-8", errors="replace")
        new_rel = fr_id.sub(lambda m: f"TASK-{m.group(1).upper()}-{m.group(2)}"
                            if m.group(0)[0].isupper() else f"task-{m.group(1)}-{m.group(2)}", rel)
        new_body, _ = rewrite(body)
        if new_rel != rel:
            print(json.dumps({"op": "move", "src": rel, "dst": new_rel}))
            ops += 1
        if new_body != body:
            print(json.dumps({
                "op": "put", "path": new_rel, "body": new_body,
                "extra": {"reason": "fr-to-task-rename-epoch"},
            }))
            ops += 1
    print(f"# {ops} ops — pipe into: python3 -m cyberos.writer apply --ndjson -",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
