#!/usr/bin/env python3
"""
migrate_fr_to_task.py — one-wave codemod: feature-request -> task, task -> subtask.

Decisions this script implements (see docs/reviews/task-rename-analysis.md §9):
  D1  the existing task@1 contract (unit of work INSIDE an FR) becomes subtask@1
  D2  all 563 FR IDs are rewritten: FR-<MOD>-<NNN> -> TASK-<MOD>-<NNN>
  D3  archives and audit evidence are rewritten too (pre-1.0, no external consumers)
  D4  one wave

The BRAIN store (.cyberos/memory/store/) is DENIED. It is not a style choice:
the audit ledger is a hash chain (AGENTS.md §6.3) with 252k rows, and every
memory file body's SHA-256 is recorded in a ledger row (§5.3). A byte-level sed
over the store breaks the chain and flips the store to FROZEN. The rename must
be expressed there as move(src,dst)+put(dst,body) through the canonical writer.
See --emit-brain-ops.

Usage:
    python3 scripts/migrate_fr_to_task.py                 # dry run, summary only
    python3 scripts/migrate_fr_to_task.py --show-files    # dry run, list files per rule
    python3 scripts/migrate_fr_to_task.py --apply         # rewrite contents + git mv paths
    python3 scripts/migrate_fr_to_task.py --verify        # assert zero residue post-apply
    python3 scripts/migrate_fr_to_task.py --emit-brain-ops > brain-rename.ndjson
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Deny-list — paths the codemod must never touch.
# CI asserts zero diff under every one of these after --apply.
# ─────────────────────────────────────────────────────────────────────────────
DENY_PREFIXES = (
    ".cyberos/",            # BRAIN store (hash chain, protocol-immutable) + regenerated payload
    "tools/caf/",           # CAF owns "BACKLOG.md" and "Task table" with unrelated meanings;
                            # 63 golden eval fixtures would be corrupted by a blind rewrite
    "dist/",                # build output, regenerated by tools/cyberos-init/build.sh
    ".vercel-out/",         # deploy output
    "docs/status/",         # ALL generated: 507 per-FR data files + the built js/css/html.
                            # Regenerated by the docs-site build. Renaming the `frs` data
                            # key and `.frs` CSS class here would desync from the generator
                            # in modules/templates/. Regenerate, do not rewrite.
    ".ruff_cache/",
    ".git/",
    "node_modules/",
    "apps/console/web/assets/",  # Vite build output (hashed names). Tracked, but generated —
                                # minified bundles hit `fr` as a random identifier fragment.
    "scripts/migrate_fr_to_task.py",   # this file
    # The analysis doc EXISTS to quote the old vocabulary. Pass 1 rewrote it into
    # nonsense ("Task to task: rename impact analysis", "if FR becomes 'task', a
    # task contains tasks"). Any document whose subject IS the rename must be
    # excluded from the rename. Same reasoning as the audit artefacts.
    "docs/reviews/task-rename-analysis.md",
    # Same principle, found when --verify failed on 509 hits in 2 files:
    #   RENAME-EPOCH.md              IS the FR-* -> TASK-* mapping. All 507 old ids
    #                                live there on purpose; that is the entire file.
    #   no-legacy-fr-vocabulary.sh   the gate's own error examples ("FR-AUTH-111 ->
    #                                TASK-AUTH-111") and its regex.
    # A file whose SUBJECT is the retired vocabulary cannot be scrubbed of it without
    # destroying the file. Verify would otherwise fail forever on its own artefacts.
    "docs/tasks/RENAME-EPOCH.md",
    ".pre-commit-hooks/no-legacy-fr-vocabulary.sh",
)

# ─────────────────────────────────────────────────────────────────────────────
# SEALED held-out acceptance tests. chmod 444 via `awh lock modules/memory/tests`
# (tools/awh/harness/stage0_verification/readonly.py), explicitly so that "the
# authoring agent cannot edit the bar it is graded against". There is no `awh
# unlock` verb — the seal is one-way by design, and breaking it must be a
# deliberate human act, not a line buried in a 2,499-file codemod.
#
# The codemod therefore refuses to touch them. It REPORTS them instead, so the
# edits are made by a human, reviewed, and recorded. `--verify` will flag the FR
# ids left inside them as residue; that is correct and intentional.
#
# Two of the three are docstring-only and cosmetic. The third is not:
#   modules/memory/tests/test_claude_code_hook.py:82
#       assert fm["source"] == "fr-memory-109"
#   modules/memory/cyberos/core/claude_code_hook.py:90
#       "source": "fr-memory-109",
# That is a coupled emitter/assertion pair on a value PERSISTED into memory-file
# frontmatter. Rewriting both keeps the test green — which is exactly the pattern
# the seal exists to catch. Decide it consciously. See --sealed.
# ─────────────────────────────────────────────────────────────────────────────
SEALED_PATHS = (
    "modules/memory/tests/test_claude_code_hook.py",
    "modules/memory/tests/test_memory_sync.py",
    "modules/memory/tests/test_sync_class.py",
)

# Binary / non-text extensions we never rewrite.
# NOTE: .svg is deliberately NOT here. SVG is text, and four architecture diagrams
# (modules/skill/docs/assets/diagrams/, modules/skill/assets/) have skill names
# baked into <text> nodes. Excluding them in pass 1 left the diagrams rendering
# `cuo/cpo/feature-request-author` after the rename. New names are shorter, so no
# label overflow.
SKIP_SUFFIXES = (
    ".png", ".jpg", ".jpeg", ".ico", ".woff", ".woff2", ".ttf",
    ".zip", ".gz", ".zst", ".binlog", ".sqlite", ".lock", ".pdf",
)

# ─────────────────────────────────────────────────────────────────────────────
# FROZEN literals. Provenance DATA, not code references. These are written into
# memory-file frontmatter, and the BRAIN store is deny-listed from this codemod.
# Rewriting the emitter while the store keeps the old value splits the data across
# two vocabularies with no migration between them. Same reasoning as the on-chain
# audit rows: history keeps its original ids.
#
# Any rule that would touch one of these is neutralised by re-substituting the
# original after the pass. Asserted by a SEALED held-out test — see §13.5.
# ─────────────────────────────────────────────────────────────────────────────
FROZEN_LITERALS = {
    "task-memory-109": "fr-memory-109",   # claude_code_hook.py frontmatter `source`

    # ── PROPER NOUNS. Same restore mechanism, different reason. ──────────────
    #
    # The token rules below rename `fr` wherever it appears as a snake_case
    # component. This script's OWN NAME contains one:
    #
    #     migrate_fr_to_task.py      ->  migrate_task_to_task.py     WRONG
    #     _cyberos_fr_migrate        ->  _cyberos_task_migrate       RIGHT
    #
    # Both are `_fr_` inside snake_case. They are structurally identical and NO
    # regex can separate them — the difference is that one is a proper noun and the
    # other is a description. The first run of the token rules rewrote 127 files to
    # cite `migrate_task_to_task.py`, a file that does not exist, and turned
    # `--grep='feature-request -> task'` (which searches the rename commit message)
    # into `--grep='task -> task'`, which matches nothing.
    #
    # Reverted, then fixed here. A codemod broad enough to catch every identifier is
    # broad enough to rename itself into nonsense.
    "migrate_task_to_task": "migrate_fr_to_task",
    "'task -> task'": "'feature-request -> task'",

    # Third instance of the same class, found when the vocabulary gate aborted the
    # rename commit itself:
    #
    #     bash: .pre-commit-hooks/no-legacy-task-vocabulary.sh: No such file
    #
    # DENY_PREFIXES protects the gate's own FILE from rewrite. It does not protect
    # .githooks/pre-commit, which CALLS that file by name — so `token:fr-kebab`
    # renamed the pointer and left the target where it was. Deny-listing a file
    # protects its contents, never its callers; every reference to a frozen name
    # from a non-frozen file needs its own entry here.
    #
    # This name must never track the rename anyway. The gate blocks the legacy FR
    # vocabulary; "no-legacy-task-vocabulary" would name a gate that blocks the
    # vocabulary we just adopted — true of the filename, false of the code.
    "no-legacy-task-vocabulary": "no-legacy-fr-vocabulary",
}

# ─────────────────────────────────────────────────────────────────────────────
# Content rules, applied IN ORDER. Longest / most-specific identifiers first so
# a short pattern cannot eat a long one.
#
# Ordering note: pass 1 frees the word `task` by moving the existing task@1
# contract to subtask@1. Only after that does pass 5 introduce `task@1` as the
# new name for feature_request@1. Running these out of order silently collapses
# the two contracts into one.
#
# Word-boundary note: \btask\b does NOT match inside "subtask" or "sub_tasks"
# (b/t and _/t are both word characters, so there is no boundary). That is what
# makes the subtask-first ordering safe.
# ─────────────────────────────────────────────────────────────────────────────
RULES: list[tuple[str, str, str]] = [
    # ── Pass 1: free the word. The existing task@1 becomes subtask@1. ────────
    ("free-word:contract-literal",   r"\btask@1\b",                    "subtask@1"),
    ("free-word:contract-id",        r"^contract_id: task$",           "contract_id: subtask"),
    ("free-word:contract-path",      r"contracts/task\b",              "contracts/subtask"),
    ("free-word:runner-module",      r"\bfr_with_tasks\b",             "task_with_subtasks"),
    ("free-word:runner-skill-id",    r"\bfr-with-tasks\b",             "task-with-subtasks"),
    ("free-word:runner-class",       r"\bFrWithTasksRunner\b",         "TaskWithSubtasksRunner"),
    ("free-word:frontmatter-field",  r"\bsub_tasks\b",                 "subtasks"),
    # subtask id sub-format: FR-007-T-03 -> TASK-007-S-03 (the -T- infix would
    # read as "task" inside a TASK- id; -S- is unambiguous).
    ("free-word:subtask-id",         r"\bFR-(\d+)-T-(\d{2})\b",        r"TASK-\1-S-\2"),

    # ── Pass 2: FR IDs. D2 = full rewrite. ──────────────────────────────────
    ("id:fr-module-num",             r"\bFR-([A-Z]{2,10})-(\d{3,4})\b", r"TASK-\1-\2"),
    # lowercase form appears in generated filenames (impl-plan-fr-mcp-003.md)
    ("id:fr-module-num-lower",       r"\bfr-([a-z]{2,10})-(\d{3,4})\b", r"task-\1-\2"),

    # ── Pass 2b: the MATCHERS. Most dangerous class in the whole rename. ────
    #
    # Renaming the IDs is not enough. ~40 regexes and globs across 20 files
    # match ON the id format, and pass 1 left every one of them saying `FR-`:
    #
    #     glob.glob(f"{root}/**/FR-*.md")          -> 0 files
    #     re.compile(r"FR-[A-Z]+-\d+")             -> 0 rows
    #     if not id.startswith("FR-")              -> skips everything
    #     /\bFR-[A-Z][A-Z0-9]*-\d+\b/g             -> 0 matches
    #     find ... -name 'FR-*.md'                 -> 0 results
    #
    # None of these THROW. They return empty. The backlog reader finds no rows,
    # the generators emit empty artefacts, and `ship-tasks` reports "no eligible
    # task" forever. A silent, total functional failure that a syntax check, a
    # type check and a smoke test all pass cleanly.
    #
    # I tried to enumerate the matcher SHAPES and lost. Each fix revealed another:
    #   FR-[A-Z]+-\d+     FR-\d+-T-\d{2}    FR-*.md        "FR-"      'FR-'
    #   FR-([A-Z]+)-\d+   f"FR-{id}-*.md"   /^FR-/         /^FR-.*\.md$/
    # After the id rewrite there is NO legitimate remaining `FR-` in source: every
    # id is TASK- now, so anything still saying FR- is either a matcher or prose,
    # and both must move. Stop enumerating shapes; rename the prefix.
    #
    # `\b` is the only thing standing between this rule and `NFR-` -> `NTASK-`,
    # which would silently destroy the non-functional-requirements pipeline.
    ("re:fr-prefix-blanket",         r"\bFR-",                         "TASK-"),
    # subtask id format changed too: FR-NNN-T-MM -> TASK-NNN-S-MM (see §7.1)
    # NOTE the doubled backslashes in the REPLACEMENT. `\d` is not a valid escape in
    # an re.sub replacement string — Python raises `re.error: bad escape \d`. The
    # pattern side wants `\\d` (a literal backslash-d in the file); the replacement
    # side wants `\\\\d` in source, i.e. `\\d` in the raw string.
    ("re:subtask-id-pattern",        r"\^TASK-\\d\+-T-\\d\{2\}\$",     r"^TASK-\\d+-S-\\d{2}$"),

    # ── Pass 3: artefact + skill + command identifiers. ──────────────────────
    ("artefact:feature-request-1",   r"\bfeature_request@1\b",         "task@1"),
    ("artefact:fr-manifest",         r"\bfr-manifest@2\b",             "task-manifest@1"),
    ("skill:fr-author",              r"\bfeature-request-author\b",    "task-author"),
    ("skill:fr-audit",               r"\bfeature-request-audit\b",     "task-audit"),
    ("cmd:ship",                     r"\bship-feature-requests\b",     "ship-tasks"),
    ("cmd:create",                   r"\bcreate-feature-requests\b",   "create-tasks"),

    # ── Pass 4: paths. Must run AFTER the skill/command rules above, because
    #     "docs/feature-requests/" and "contracts/feature-request/" share a stem
    #     with the skill names. ─────────────────────────────────────────────────
    ("path:docs-dir",                r"docs/feature-requests\b",       "docs/tasks"),
    ("path:contract-dir",            r"contracts/feature-request\b",   "contracts/task"),

    # ── Pass 5: frontmatter fields carrying FR IDs. ──────────────────────────
    ("field:related-frs",            r"\brelated_frs\b",               "related_tasks"),

    # ── Pass 5a: FILENAME references.
    #
    # PASS-3 ADDITIONS. `git mv` renames a file; it does NOT rename the places
    # that CALL it by name. Pass 1 moved render-fr-pages.mjs -> render-task-pages.mjs
    # while tools/docs-site/build.sh went on invoking `node render-fr-pages.mjs`,
    # which is what broke the docs-site build. Same for every other moved script.
    #
    # Rule of thumb for any future rename: for each entry in PATH_RENAMES there
    # MUST be a matching content rule for its basename, or the move is a landmine.
    ("file:render-fr-catalog",       r"render-fr-catalog",             "render-task-catalog"),
    ("file:render-fr-pages",         r"render-fr-pages",               "render-task-pages"),
    ("file:test-render-fr-pages",    r"test_render_fr_pages",          "test_render_task_pages"),
    ("file:migrate-improvement",     r"migrate_improvement_to_fr",     "migrate_improvement_to_task"),
    ("file:migrate-fr-layout",       r"migrate_fr_layout",             "migrate_task_layout"),
    ("file:test-fr-layout",          r"test_fr_layout",                "test_task_layout"),
    ("file:repair-fr-yaml",          r"repair_fr_yaml",                "repair_task_yaml"),
    ("file:rebaseline-fr-status",    r"rebaseline_fr_status",          "rebaseline_task_status"),
    ("file:awh-goldenset-from-fr",   r"awh_goldenset_from_fr",         "awh_goldenset_from_task"),
    ("file:fr-migrate-sh",           r"\bfr-migrate\b",                "task-migrate"),
    ("file:ship-your-first-fr",      r"ship-your-first-fr\b",          "ship-your-first-task"),

    # ── Pass 5a2: `fr` as a snake_case / kebab TOKEN. ───────────────────────
    #
    # Pass 1 enumerated six identifiers (fr_id, fr_row, FrRow, _FR_ROW_RE, _FR_ID_RE,
    # frs) and missed 37 more across 357 sites: fr_path, fr_root, fr_dir, fr_file,
    # ship_fr, fr_routed_back, fr_list_sorted, next_fr, dep_fr_id, _cyberos_fr_migrate,
    # CYBEROS_FR_BASE, ...
    #
    # Enumerating names does not converge — every pass found more. Rename the TOKEN.
    # `\b` is useless here: `_` is a word character, so `\bfr_` never matches inside
    # `_cyberos_fr_migrate`. That is precisely how it survived four passes.
    #
    # Protected by FROZEN_LITERALS: this script's own name (see the note there).
    ("token:fr_-lead",               r"(?<![A-Za-z0-9])fr_",           "task_"),
    ("token:_fr-tail",               r"_fr(?![A-Za-z0-9_])",           "_task"),
    ("token:FR_-const",              r"(?<![A-Za-z0-9])FR_",           "TASK_"),
    ("token:fr-kebab",               r"(?<![A-Za-z0-9_])fr-(?=[a-z])", "task-"),

    # ── Pass 5b: code identifiers. D5 = task_id, module-scoped.
    #     Safe at the rename site: `fr_id` appears only in modules/cuo,
    #     modules/skill, scripts/ and tools/ — never in services/mcp-gateway
    #     (which owns mcp_tasks.task_id) or tools/awh (eval task_id). The
    #     overload is repo-wide and semantic, not a shadowing bug. It is
    #     recorded in an ADR and enforced by check_sep986_naming.sh. ─────────
    ("ident:fr-id",                  r"\bfr_id\b",                     "task_id"),
    ("ident:fr-row",                 r"\bfr_row\b",                    "task_row"),
    ("ident:FrRow",                  r"\bFrRow\b",                     "TaskRow"),
    ("ident:FR_ROW_RE",              r"\b_FR_ROW_RE\b",                "_TASK_ROW_RE"),
    ("ident:FR_ID_RE",               r"\b_FR_ID_RE\b",                 "_TASK_ID_RE"),
    # WAS: r"\bfrs\b(?=\s*[:=\)\],])" — scoped to DEFINITION sites only.
    # That renamed `def select_next(frs: list)` -> `(tasks: list)` and
    # `frs = {}` -> `tasks = {}` while leaving every USE site (`for f in frs`,
    # `frs[k]`, `dep in frs`) pointing at a name that no longer exists.
    # Result: NameError at runtime in ship_manifest.select_next(), plus two
    # project-cleanup generators silently half-renamed. Syntax stayed valid,
    # so nothing caught it until the test suite ran.
    #
    # An identifier rename is all-or-nothing. Rename the whole symbol.
    # `(?<![."'])...(?![."'])` keeps this off the CSS CLASS `frs`, which is a
    # different thing wearing the same three letters:
    #     status-app.js   '<div class="frs">'        <- markup, must not change
    #     status.css      .frs { display: flex; }    <- and `.tasks` ALREADY exists
    #                                                   there meaning something else,
    #                                                   so renaming it would collide
    # The Python identifier this rule is for is never quoted or dot-prefixed.
    ("ident:frs-var",                r"(?<![.\"'])\bfrs\b(?![.\"'])",  "tasks"),

    # ── Pass 6: remaining identifiers, then prose. ───────────────────────────
    #
    # PASS-2 ADDITIONS. The first run left ~90 sites behind because `_` is a word
    # character, so `\bfeature_request\b` never matched INSIDE a longer snake_case
    # identifier:
    #     _apply_feature_request_audit      (cuo/core/applier.py — function name)
    #     feature_request_audit:            (backlog-state-update envelope FIELD —
    #                                        required by the BSU rubric for the
    #                                        draft -> ready_to_implement transition)
    #     feature_request_author_validates  (skill-broker test fn names)
    # Handle the compounds explicitly, longest first, then drop the boundary.
    ("ident:apply-fr-audit-fn",      r"_apply_feature_request_audit",  "_apply_task_audit"),
    ("ident:fr-audit-field",         r"feature_request_audit",         "task_audit"),
    ("ident:fr-author-field",        r"feature_request_author",        "task_author"),
    ("ident:feature-request-snake",  r"feature_request",               "task"),

    ("ident:feature-requests-kebab", r"\bfeature-requests\b",          "tasks"),
    ("ident:feature-request-kebab",  r"\bfeature-request\b",           "task"),

    # Prose. The first run missed hyphenated Title Case ("Phase F - Feature-Request
    # Authoring") and sentence case ("Feature request — engineering-spec@1", the
    # user-visible kind label on every rendered docs page).
    ("prose:Feature-Requests-hyph",  r"\bFeature-Requests\b",          "Tasks"),
    ("prose:Feature-Request-hyph",   r"\bFeature-Request\b",           "Task"),
    ("prose:Feature-Requests",       r"\bFeature Requests\b",          "Tasks"),
    ("prose:Feature-requests-sent",  r"\bFeature requests\b",          "Tasks"),
    ("prose:Feature-Request",        r"\bFeature Request\b",           "Task"),
    ("prose:Feature-request-sent",   r"\bFeature request\b",           "Task"),
    ("prose:feature-requests",       r"\bfeature requests\b",          "tasks"),
    ("prose:feature-request",        r"\bfeature request\b",           "task"),
]

# ─────────────────────────────────────────────────────────────────────────────
# PROSE-ONLY rules. These MUST NOT run on source code.
#
# The bare abbreviation `FR` is prose, and rewriting it to `task` produces
# lowercase text mid-sentence, so it needs a capitalisation repair afterwards.
# That repair is where it bit: the rule
#
#     ^(\s*(?:[-*>#]+\s+|\d+\.\s+)?)task\b   ->   \1Task
#
# is correct for a markdown bullet or heading, and catastrophic in Python, where
# it rewrote a dataclass field
#
#     task: str      ->      Task: str        (episode.py, 21 tests red)
#
# and every keyword argument at line start. `TaskRow` / `TaskCreate` survived only
# because \b needs a non-word char after "Task".
#
# Lesson: a prose rule applied to code is not a typo, it is a different program.
# Gate every prose rule on the file extension.
# ─────────────────────────────────────────────────────────────────────────────
PROSE_ONLY_SUFFIXES = (".md", ".txt", ".html", ".mdc", ".rst")

# ─────────────────────────────────────────────────────────────────────────────
# The MIRROR of the prose problem, and the third time this lesson showed up.
#
# `ident:frs-var` renames the Python identifier `frs` -> `tasks`. Correct in code.
# In prose it fires on things that are not identifiers at all:
#
#     "manifest_path": "./frs/manifest.json"      an envelope example path
#     via the existing `migrate-frs.sh --page`    a historical filename
#     documented in `implement-backlog-frs`       a retired skill name
#     website/build/data/{nfrs,risks,frs}.json    a data filename
#
# Rewriting those produces nonsense and makes `--verify` fail forever on content
# that is correct. A gate that can never pass is a gate people learn to ignore —
# which is the exact failure mode this session kept finding elsewhere (`declare -A`
# silently passing on bash 3.2, 29 trigger tests green against a monkeypatched fake).
#
# So: identifier rules run ONLY on code, prose rules run ONLY on prose, and the ones
# that are safe everywhere (ids, paths, artefact names) run on both.
# ─────────────────────────────────────────────────────────────────────────────
CODE_ONLY_RULES = frozenset({
    "ident:frs-var",
    "ident:fr-id", "ident:fr-row", "ident:FrRow",
    "ident:FR_ROW_RE", "ident:FR_ID_RE",
    "ident:apply-fr-audit-fn",
})
CODE_SUFFIXES = (".py", ".rs", ".mjs", ".js", ".ts", ".tsx", ".sh", ".yaml", ".yml",
                 ".json", ".toml")

PROSE_RULES: list[tuple[str, str, str]] = [
    ("prose:FRs",                    r"\bFRs\b",                       "tasks"),
    ("prose:FR",                     r"\bFR\b",                        "task"),
]

# Applied only after PROSE_RULES, only to PROSE_ONLY_SUFFIXES.
PROSE_FIXUPS: list[tuple[str, str]] = [
    (r"(?m)^(\s*(?:[-*>#]+\s+|\d+\.\s+)?)task\b", r"\1Task"),  # bullet / heading start
    (r"([.!?]\s+)task\b",                         r"\1Task"),  # sentence start
    (r"(\|\s*)task(\s*\|)",                       r"\1Task\2"),  # lone table cell
    # "an FR" -> "an task". FR is read "eff-arr" (vowel sound); task is not.
    (r"\bAn task\b", "A task"), (r"\ban task\b", "a task"),
    (r"\bAn Task\b", "A Task"), (r"\ban Task\b", "a Task"),
]

# The bare `FR` abbreviation is NOT in RULES. It is 2 characters and appears
# inside unrelated words, inside the FR-<MOD>-<NNN> ids handled above, and in
# third-party prose. --residue reports every remaining site for a human pass.
# ─────────────────────────────────────────────────────────────────────────────
# RULE-INDEPENDENT completeness scan.
#
# --verify used to re-run the RULES and report what THEY still matched. That is a
# coverage check wearing a completeness check's clothes: a missing rule is
# indistinguishable from a clean tree. It reported "0 residue" while 357 `fr_*`
# identifiers were still in the tree across 37 names the rules had never heard of.
#
# Same shape as every other false-green this migration turned up: bash 3.2
# swallowing `declare -A`, 29 trigger tests passing against a monkeypatched
# `classify`, a parser returning 0 rows because its regex matched nothing.
#
# These patterns know nothing about the rules. They ask the only question that
# matters: is the retired vocabulary still here?
# ─────────────────────────────────────────────────────────────────────────────
# Rule-INDEPENDENT. These answer "is the retired vocabulary still here?", never "did my
# rules fire?" — see §14.6. Three gaps found on 2026-07-15, each of which let a live bug
# through a --verify that reported `none`:
#
#   1. `FR-id-prefix` was `\bFR-[A-Z0-9]`. Source text `/\bFR-[A-Z]...` (a JS regex
#      literal) has the letter `b` immediately before `FR` — the tail of the escape
#      `\b`. `b` is a word char, so `\b` asserts no boundary and the pattern MISSED.
#      A word-boundary check defeated by the letter inside `\b`. It also required
#      [A-Z0-9] after the dash, which `FR-[A-Z]` (literal bracket) fails.
#      -> Now a bare literal. Any `FR-` at all is residue.
#      Cost of the miss: render-status-hub.mjs kept `const TASKID = /\bFR-.../`,
#      `cited` came back [] for every release, and the changelog -> task binding was
#      dead on the live status page.
#
#   2. Bare lowercase `fr` as a path segment or word (`docs/status/data/fr/`) matched
#      nothing: `bare-FR-abbrev` is uppercase-only, `fr-kebab` needs a trailing dash,
#      `fr_-identifier` needs an underscore. Cost: audit-fleet.sh counted 0 chunks
#      against 509 specs and flagged every healthy repo `no-spec-chunks`.
#
#   3. `-fr` as a token TAIL (`data-fr="..."`) matched nothing for the same reason —
#      every rule keys on `fr-` or `fr_`, never `-fr`.
#
# The shape of all three: a pattern written to describe the rules, not the vocabulary.
RESIDUE_PATTERNS = [
    ("bare-FR-abbrev",   re.compile(r"(?<![A-Za-z0-9_-])FRs?(?![A-Za-z0-9_-])")),
    # `(?<!N)` because NFR- (non-functional requirement) legitimately contains FR- and is
    # NOT part of this rename — 498 live ids under docs/non-functional-requirements/.
    # Not \b: the JS source `/\bFR-.../` has the letter `b` before FR, which kills the
    # boundary (that is exactly what hid the dead TASKID regex).
    ("FR-id-prefix",     re.compile(r"(?<!N)FR-")),
    ("feature-request",  re.compile(r"(?i)feature[-_ ]request")),
    ("fr_-identifier",   re.compile(r"(?<![A-Za-z0-9])fr_|_fr(?![A-Za-z0-9_])|(?<![A-Za-z0-9])FR_")),
    ("fr-kebab",         re.compile(r"(?<![A-Za-z0-9_])fr-(?=[a-z])")),
    ("fr-bare-token",    re.compile(r"(?<![A-Za-z0-9_-])fr(?![A-Za-z0-9_-])")),
    ("fr-token-tail",    re.compile(r"[-/]fr(?![A-Za-z0-9_])")),
]

# Literals that MUST survive the rename, on any line, comment or not. Each is a
# reference whose SUBJECT is the retired vocabulary — the same reasoning that
# deny-lists RENAME-EPOCH.md, and the reason --verify can reach exit 0 at all:
#
#   migrate_fr_to_task.py       this script's own filename (a proper noun)
#   fr-memory-109               FROZEN provenance value, written into memory-file
#                               frontmatter; the BRAIN still holds it (FROZEN_LITERALS)
#   'feature-request -> task'   the git-log --grep key that finds the rename commit;
#                               the old words ARE the search key
#
# A residue scan that flags these can never pass, and a gate that can never pass is
# one people learn to route around.
RESIDUE_EXEMPT = (
    "migrate_fr_to_task",
    "fr-memory-109",
    "'feature-request -> task'",
    "no-legacy-fr-vocabulary",
)

# Path renames (git mv). Applied after content rewrite.
PATH_RENAMES = [
    ("docs/feature-requests",                    "docs/tasks"),
    ("modules/skill/contracts/task",             "modules/skill/contracts/subtask"),
    ("modules/skill/contracts/feature-request",  "modules/skill/contracts/task"),
    ("modules/skill/feature-request-author",     "modules/skill/task-author"),
    ("modules/skill/feature-request-audit",      "modules/skill/task-audit"),
    ("modules/skill/runners/fr_with_tasks.py",   "modules/skill/runners/task_with_subtasks.py"),
    ("modules/cuo/chief-technology-officer/workflows/ship-feature-requests.md",
     "modules/cuo/chief-technology-officer/workflows/ship-tasks.md"),
    ("tools/cyberos-init/plugin/commands/create-feature-requests.md",
     "tools/cyberos-init/plugin/commands/create-tasks.md"),
    ("scripts/migrate_fr_layout.py",             "scripts/migrate_task_layout.py"),
    ("scripts/repair_fr_yaml.py",                "scripts/repair_task_yaml.py"),
    ("scripts/rebaseline_fr_status.py",          "scripts/rebaseline_task_status.py"),
    ("scripts/awh_goldenset_from_fr.py",         "scripts/awh_goldenset_from_task.py"),
    ("tools/cyberos-init/lib/fr-migrate.sh",     "tools/cyberos-init/lib/task-migrate.sh"),
    ("tools/docs-site/render-fr-catalog.mjs",    "tools/docs-site/render-task-catalog.mjs"),
    ("tools/docs-site/render-fr-pages.mjs",      "tools/docs-site/render-task-pages.mjs"),
    # PASS-3: files pass 1 forgot entirely.
    ("scripts/migrate_improvement_to_fr.py",     "scripts/migrate_improvement_to_task.py"),
    ("scripts/tests/test_fr_layout.sh",          "scripts/tests/test_task_layout.sh"),
    ("tools/docs-site/tests/test_render_fr_pages.sh",
     "tools/docs-site/tests/test_render_task_pages.sh"),
    ("modules/cuo/docs/guides/ship-your-first-fr.md",
     "modules/cuo/docs/guides/ship-your-first-task.md"),
]

# INVARIANT: every PATH_RENAMES entry needs a content rule for its basename,
# or callers keep invoking a filename that no longer exists. Checked by --verify.
def unreferenced_renames() -> list[str]:
    stems = {Path(src).stem.replace(".", "") for src, _ in PATH_RENAMES}
    covered = " ".join(pat for _n, pat, _r in RULES)
    return sorted(s for s in stems
                  if ("fr" in s.lower().split("_") or "-fr-" in s or "_fr_" in s)
                  and s not in covered)

# ─────────────────────────────────────────────────────────────────────────────
# IDEMPOTENCY GUARD.
#
# Three rules are ONE-SHOT. They free the word `task` by demoting the old
# task@1 contract to subtask@1. Once pass 1 has run, `task@1` means the NEW
# thing (the former feature_request@1). Re-running them would demote THAT to
# subtask@1 and collapse both contracts into one — silently, across 216 sites.
#
# Every other rule is idempotent: its left-hand side no longer exists after the
# first run, so a second pass is a no-op.
#
# The guard keys off the on-disk marker that pass 1 leaves behind.
# ─────────────────────────────────────────────────────────────────────────────
ONE_SHOT_RULES = frozenset({
    "free-word:contract-literal",   # task@1 -> subtask@1
    "free-word:contract-id",        # contract_id: task -> subtask
    "free-word:contract-path",      # contracts/task -> contracts/subtask
})

# The PATH rename is one-shot for the same reason, and guarding only the content
# rules is not enough. Learned the hard way on the pass-2 run: `contracts/task ->
# contracts/subtask` re-fired and swallowed the NEW task contract into
# contracts/subtask/task/, taking STATUS-REFERENCE.md with it and breaking
# build.sh. An "is the source absent?" check does NOT catch this — the source very
# much exists, it is just a different thing now.
ONE_SHOT_PATH_RENAMES = frozenset({
    ("modules/skill/contracts/task", "modules/skill/contracts/subtask"),
})


def word_already_freed(root: Path) -> bool:
    """True once pass 1 has demoted the old task@1 contract to subtask@1."""
    return (root / "modules" / "skill" / "contracts" / "subtask").is_dir()


COMPILED_ALL = [(name, re.compile(pat, re.MULTILINE), rep) for name, pat, rep in RULES]
COMPILED = COMPILED_ALL   # rebound in main() once the repo root is known


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return Path(out.stdout.strip())


def tracked_files(root: Path) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=root, capture_output=True, text=True, check=True,
    )
    return [p for p in out.stdout.split("\0") if p]


# ─────────────────────────────────────────────────────────────────────────────
# Tracked SYMLINKS. git ls-files lists them like ordinary paths, so a naive
# read_text() either explodes (IsADirectoryError, when the link points at a
# directory) or — far worse — writes THROUGH the link into a target that is
# itself tracked and already rewritten.
#
# This repo has six:
#   AGENTS.md                                 -> modules/memory/cyberos/data/AGENTS.md
#   CLAUDE.md                                 -> modules/memory/cyberos/data/AGENTS.md
#   .codex/skills/ship-feature-requests       -> ../../.cyberos/plugin/skills/ship-feature-requests
#   .commandcode/skills/ship-feature-requests -> (same)
#   .grok/skills/ship-feature-requests        -> (same)
#   .opencode/skill/ship-feature-requests     -> (same)
#
# AGENTS.md and CLAUDE.md point at the SAME file. Planning three edits that all
# write to one target is how you corrupt the memory protocol: the third read
# would see the already-rewritten body and fire the one-shot `task@1 ->
# subtask@1` rule on it. The two-phase apply (plan everything, then write)
# happens to prevent this, but do not rely on that — skip links outright. Their
# targets are tracked separately and get rewritten on their own.
# ─────────────────────────────────────────────────────────────────────────────
SYMLINK_RENAMES = (
    (".codex/skills",       "ship-feature-requests", "ship-tasks"),
    (".commandcode/skills", "ship-feature-requests", "ship-tasks"),
    (".grok/skills",        "ship-feature-requests", "ship-tasks"),
    (".opencode/skill",     "ship-feature-requests", "ship-tasks"),
    (".claude/skills",      "ship-feature-requests", "ship-tasks"),   # gitignored, fix anyway
)


def in_scope(rel: str) -> bool:
    if any(rel.startswith(p) for p in DENY_PREFIXES):
        return False
    if rel in SEALED_PATHS:
        return False
    if any(rel.endswith(s) for s in SKIP_SUFFIXES):
        return False
    return True


def fix_symlinks(root: Path) -> None:
    """Retarget the agent-tool skill symlinks: ship-feature-requests -> ship-tasks.

    These are how Claude Code, Codex, Grok, opencode and commandcode discover the
    workflow. Four of the five are TRACKED. Leave them and every agent keeps
    resolving a skill name that no longer exists the moment build.sh regenerates
    the payload.
    """
    print("\n--- agent skill symlinks ---")
    for d, old, new in SYMLINK_RENAMES:
        old_p = root / d / old
        new_p = root / d / new
        if not old_p.is_symlink():
            print(f"skip (absent)  {d}/{old}")
            continue
        target = __import__("os").readlink(old_p)
        new_target = target.replace(old, new)
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", f"{d}/{old}"],
            cwd=root, capture_output=True, text=True,
        ).returncode == 0
        if new_p.is_symlink() or new_p.exists():
            print(f"skip (done)    {d}/{new} already exists")
            continue
        if tracked:
            subprocess.run(["git", "rm", "-q", "--cached", f"{d}/{old}"], cwd=root, check=True)
        old_p.unlink()
        new_p.symlink_to(new_target)
        if tracked:
            # -f is REQUIRED: these agent dirs are gitignored, and the old links
            # were force-added. Without -f, git refuses and the run dies here,
            # halfway through the symlink set.
            subprocess.run(["git", "add", "-f", f"{d}/{new}"], cwd=root, check=True)
        print(f"retargeted     {d}/{new} -> {new_target}"
              f"{'  (tracked)' if tracked else '  (gitignored)'}")
    print("\n  Also update the managed block in .gitignore (it names the OLD paths),")
    print("  and rebuild the payload so the symlink targets actually exist:")
    print("      bash tools/cyberos-init/build.sh")


def report_sealed(root: Path) -> None:
    """Show, but never write, the edits the codemod would make to sealed tests."""
    print("\n--- SEALED held-out tests (codemod refuses to write; do these by hand) ---")
    for rel in SEALED_PATHS:
        p = root / rel
        if not p.exists():
            print(f"  absent: {rel}")
            continue
        src = p.read_text(encoding="utf-8")
        new, hits = rewrite(src, rel)
        if not hits:
            print(f"  clean:  {rel}")
            continue
        print(f"\n  {rel}   ({sum(hits.values())} edits)")
        for i, (a, b) in enumerate(zip(src.splitlines(), new.splitlines()), 1):
            if a != b:
                kind = "DATA" if not a.lstrip().startswith(('"""', "#", "'''")) else "docstring"
                print(f"    L{i} [{kind}]")
                print(f"      - {a.strip()[:96]}")
                print(f"      + {b.strip()[:96]}")
    print("""
  To apply, as a deliberate human act:
      chmod u+w modules/memory/tests/test_claude_code_hook.py \\
                modules/memory/tests/test_memory_sync.py \\
                modules/memory/tests/test_sync_class.py
      # edit the lines above by hand, then re-seal:
      python -m awh lock modules/memory/tests
      git commit -m "test(memory): unseal held-out tests for fr->task rename, re-sealed"

  Before you touch test_claude_code_hook.py L82, decide the DATA question:
  claude_code_hook.py:90 writes `"source": "fr-memory-109"` into memory-file
  frontmatter. The BRAIN has 0 files carrying it today, so rewriting is free NOW.
  If the hook had ever run, you would have persisted data on one vocabulary and
  new code on another, with the BRAIN deny-listed from this codemod. Either
  rewrite both and note it, or leave `source` as a frozen provenance tag.""")


def _is_comment(line: str) -> bool:
    """A comment / blockquote line — exempt from rewriting (see rewrite())."""
    s = line.lstrip()
    return s.startswith(("#", "//", "*", ">", "<!--", '"""'))


def rewrite(text: str, rel: str = "") -> tuple[str, Counter]:
    """Rewrite one file's text. `rel` gates the code-only rules (see CODE_ONLY_RULES).

    `rel=""` means "no file context" — code-only rules are skipped, because guessing
    wrong on prose is the expensive direction: it corrupts a path or a historical
    filename, and nobody notices until something tries to resolve it.
    """
    original = text
    is_code = rel.endswith(CODE_SUFFIXES)
    hits: Counter = Counter()

    # A COMMENT that explains the retired vocabulary must keep it, or it stops
    # explaining anything. Same exemption the pre-commit hook carries, and the last
    # three files --verify flagged were all this shape:
    #   .githooks/pre-commit  "# ...why it sat there full of stale FR-*.js chunks"
    #   task-author/SKILL.md  "# `FR-` id or a `feature-request` string, so no rule
    #                          matched it"
    #   status-app.js         "// NOTE: the `frs` CSS CLASS below is NOT renamed"
    # Rewriting those turns a true sentence into a false one. Rewrite line by line
    # and leave comment lines alone.
    lines = text.split("\n")
    for i, ln in enumerate(lines):
        if _is_comment(ln):
            continue
        for name, pat, rep in COMPILED:
            if name in CODE_ONLY_RULES and not is_code:
                continue
            ln, n = pat.subn(rep, ln)
            if n:
                hits[name] += n
        lines[i] = ln
    text = "\n".join(lines)
    # Restore frozen provenance literals the rules above may have swept up.
    for wrong, right in FROZEN_LITERALS.items():
        if wrong in text:
            text = text.replace(wrong, right)
            hits["frozen:restored"] += 1

    # A rule that fired and was then fully undone by the frozen-literal restore is
    # not a change. Reporting it as one made `--verify` fail on claude_code_hook.py
    # forever: `id:fr-module-num-lower` rewrote fr-memory-109 -> task-memory-109,
    # FROZEN_LITERALS put it straight back, net text identical — and the hit counter
    # still claimed an edit. A verify that flags a file it does not modify is lying.
    if text == original:
        return text, Counter()
    return text, hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write changes and git mv paths")
    ap.add_argument("--show-files", action="store_true", help="list files touched per rule")
    ap.add_argument("--verify", action="store_true", help="assert zero residue; exit 1 if any")
    ap.add_argument("--residue", action="store_true", help="report sites the rules cannot reach")
    ap.add_argument("--emit-brain-ops", action="store_true",
                    help="emit NDJSON move/put ops for the BRAIN store (do not sed it)")
    ap.add_argument("--sealed", action="store_true",
                    help="show the edits the codemod refuses to make to sealed held-out tests")
    ap.add_argument("--fix-symlinks", action="store_true",
                    help="retarget the agent skill symlinks only (no dirty-tree guard)")
    args = ap.parse_args()

    root = repo_root()

    if args.fix_symlinks:
        fix_symlinks(root)
        return 0

    # ── Idempotency guard: disarm the one-shot rules once pass 1 has run. ───
    global COMPILED
    freed = word_already_freed(root)
    if freed:
        COMPILED = [t for t in COMPILED_ALL if t[0] not in ONE_SHOT_RULES]
        # stderr, not stdout: --emit-brain-ops writes NDJSON to stdout and any
        # human-readable chatter mixed in there corrupts the op stream.
        print("note: contracts/subtask/ exists -> pass 1 already ran.", file=sys.stderr)
        print("      one-shot rules DISARMED (they would demote the new task@1 "
              "to subtask@1):", file=sys.stderr)
        for r in sorted(ONE_SHOT_RULES):
            print(f"        {r}", file=sys.stderr)
        print(file=sys.stderr)

    files = [f for f in tracked_files(root) if in_scope(f)]

    if args.emit_brain_ops:
        return emit_brain_ops(root)

    if args.sealed:
        report_sealed(root)
        return 0

    # ── Guard 1: refuse to apply to a dirty tree. ───────────────────────────
    # `git checkout -- .` must be a valid, complete undo. If the tree already
    # has uncommitted work, a failed apply cannot be cleanly reverted.
    if args.apply:
        dirty = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=root, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if dirty:
            print("REFUSING TO APPLY: working tree is dirty.", file=sys.stderr)
            print("Commit or stash first, so `git checkout -- .` is a clean undo.\n",
                  file=sys.stderr)
            print(dirty, file=sys.stderr)
            return 2

    total: Counter = Counter()
    touched: dict[str, list[str]] = {}
    residue: Counter = Counter()
    residue_files: dict[str, set[str]] = {}
    plan: list[tuple[Path, str]] = []   # (path, new_content) — nothing is written yet

    # ── Phase 1: plan every edit in memory. Write nothing. ──────────────────
    skipped_links = 0
    for rel in files:
        path = root / rel
        # Never read or write through a symlink. See SYMLINK_RENAMES above:
        # AGENTS.md and CLAUDE.md both point at modules/memory/cyberos/data/AGENTS.md,
        # and four skill links point at directories. Their targets are tracked
        # separately and get rewritten on their own.
        if path.is_symlink():
            skipped_links += 1
            continue
        try:
            src = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError, IsADirectoryError):
            continue

        new, hits = rewrite(src, rel)

        if args.residue or args.verify:
            # Comment lines are exempt here for the same reason rewrite() skips them:
            # a comment explaining the retired vocabulary has to contain it. Without
            # this, --verify can never reach exit 0 on its own documentation, and a
            # gate that can never pass is one people learn to route around — the exact
            # failure this session kept finding (bash 3.2 `declare -A` silently
            # passing; 29 trigger tests green against a monkeypatched fake).
            probe = "\n".join(
                l for l in (src if args.verify else new).split("\n")
                if not _is_comment(l) and not any(x in l for x in RESIDUE_EXEMPT))
            for rname, rpat in RESIDUE_PATTERNS:
                n = len(rpat.findall(probe))
                if n:
                    residue[rname] += n
                    residue_files.setdefault(rname, set()).add(rel)

        if hits:
            total.update(hits)
            for k in hits:
                touched.setdefault(k, []).append(rel)
            plan.append((path, new))

    changed_files = len(plan)

    # ── Guard 2: pre-flight writability. Abort BEFORE the first write. ──────
    # A crash halfway through leaves a half-renamed repo, which is far worse
    # than not starting. Learned the hard way: an ACL-restricted file killed
    # the first run at file ~1349 of 2498.
    if args.apply:
        unwritable = [p for p, _ in plan if not p.parent.is_dir() or (
            p.exists() and not __import__("os").access(p, __import__("os").W_OK))]
        if unwritable:
            print(f"REFUSING TO APPLY: {len(unwritable)} planned files are not writable.",
                  file=sys.stderr)
            for p in unwritable[:20]:
                print(f"  {p.relative_to(root)}", file=sys.stderr)
            return 2

    # ── Phase 2: commit the plan to disk. ───────────────────────────────────
    if args.apply:
        for path, new in plan:
            path.write_text(new, encoding="utf-8")

    mode = "APPLY" if args.apply else ("VERIFY" if args.verify else "DRY RUN")
    print(f"=== migrate_fr_to_task — {mode} ===")
    print(f"in-scope tracked files : {len(files)}")
    print(f"symlinks skipped       : {skipped_links}  (targets rewritten separately)")
    print(f"files with edits       : {changed_files}")
    print(f"total substitutions    : {sum(total.values())}\n")

    print(f"{'rule':32} {'hits':>7}  files")
    for name, _p, _r in RULES:
        n = total.get(name, 0)
        if n:
            print(f"{name:32} {n:7}  {len(touched.get(name, []))}")
            if args.show_files:
                for f in sorted(touched[name])[:12]:
                    print(f"{'':34}   {f}")
                extra = len(touched[name]) - 12
                if extra > 0:
                    print(f"{'':34}   ... +{extra} more")

    if args.residue or args.verify:
        print(f"\n--- residue (needs a human pass) ---")
        if not residue:
            print("none")
        for rname, n in residue.most_common():
            print(f"{rname:32} {n:7}  {len(residue_files[rname])} files")
            if args.show_files:
                for f in sorted(residue_files[rname])[:10]:
                    print(f"{'':34}   {f}")

        # ── FILENAME residue ────────────────────────────────────────────────────
        # Everything above reads file CONTENTS. Nothing read the NAMES until
        # 2026-07-15, and that whole dimension was invisible to a check reporting
        # "none". What it hid:
        #
        #   306  docs/tasks/_{audits,archive}/**/FR-*.md   each contradicting its own
        #        frontmatter (`task_id: TASK-AI-001` inside `FR-AI-001-*.audit.md`)
        #     1  tools/cyberos-init/templates/FR-TEMPLATE.md — while install.sh's
        #        onboarding block told every new user to `cp ... TASK-TEMPLATE.md`.
        #        The first command a new user runs, failing on No such file.
        #     1  11-feature-request-author-...-sequence.svg — the reference in
        #        appendices.md was rewritten to 11-task-author-..., the file was not.
        #        Broke `docs-site build` on every commit ("MISSING ASSET").
        #
        # Same shape as the vocabulary gate renaming its own caller: a codemod
        # rewrites text, so it moves references and leaves targets. `git mv` is a
        # different operation from `re.sub`, and only PATH_RENAMES did it — for the
        # directories someone remembered to list.
        #
        # `(?<!N)` keeps NFR- (non-functional requirements): ~470 legitimate files.
        name_pat = re.compile(r"(?<!N)FR-|feature[-_]request|(?<![A-Za-z0-9])fr[-_]")
        bad_names = [f for f in files
                     if name_pat.search(Path(f).name)
                     and not any(x in f for x in RESIDUE_EXEMPT)]
        print(f"\n--- filename residue ---")
        if not bad_names:
            print("none")
        else:
            print(f"{'old vocabulary in FILENAME':32} {len(bad_names):7}  files")
            for f in sorted(bad_names)[:10]:
                print(f"{'':34}   {f}")
            if len(bad_names) > 10:
                print(f"{'':34}   ... +{len(bad_names) - 10} more")
            residue["filename"] = len(bad_names)

    if args.apply:
        print("\n--- path renames (git mv) ---")
        for src, dst in PATH_RENAMES:
            if freed and (src, dst) in ONE_SHOT_PATH_RENAMES:
                print(f"skip (ONE-SHOT, already ran)  {src} -> {dst}")
                continue
            s, d = root / src, root / dst
            if not s.exists():
                print(f"skip (absent)  {src}")
                continue
            if d.exists():
                # git mv into an existing directory NESTS instead of failing.
                # That is how contracts/task ended up inside contracts/subtask/task/.
                print(f"REFUSING       {src} -> {dst}  (destination exists; would nest)")
                continue
            d.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(["git", "mv", src, dst], cwd=root, check=True)
            print(f"moved          {src} -> {dst}")

        # ── The 563 per-spec directories: docs/tasks/<mod>/FR-MOD-NNN-slug/ ──
        print("\n--- spec directory renames (FR-* -> TASK-*) ---")
        tasks_root = root / "docs" / "tasks"
        moved = 0
        if tasks_root.is_dir():
            # Deepest-first so a parent rename cannot invalidate a child path.
            cands = sorted(
                (p for p in tasks_root.rglob("*") if p.is_dir() and p.name.startswith("FR-")),
                key=lambda p: len(p.parts), reverse=True,
            )
            for p in cands:
                new_name = re.sub(r"^FR-", "TASK-", p.name)
                subprocess.run(
                    ["git", "mv", str(p.relative_to(root)),
                     str((p.parent / new_name).relative_to(root))],
                    cwd=root, check=True,
                )
                moved += 1
        print(f"renamed {moved} spec directories")

        fix_symlinks(root)

        print("\n--- next, by hand ---")
        print("  1. the 13 agent-config files (.cursorrules, .windsurfrules, .grok/GROK.md,")
        print("     .github/copilot-instructions.md, .agents/rules/, .cursor/rules/, AGENTS.md,")
        print("     CLAUDE.md, GEMINI.md, .gitignore managed block, .githooks/pre-commit)")
        print("  2. the bare-FR prose pass (see --residue; 2-char token, needs review)")
        print("  3. .git-blame-ignore-revs <- sha of this commit")
        print("  4. --emit-brain-ops | python3 -m cyberos.writer apply   (never sed the store)")

    if args.verify and residue:
        print("\nVERIFY FAILED: residue remains.")
        return 1
    return 0


def emit_brain_ops(root: Path) -> int:
    """The BRAIN store cannot be sed'd. Emit protocol-legal move+put ops instead.

    Every memory file body's SHA-256 is recorded in an audit row (AGENTS.md §5.3),
    and the ledger is a hash chain (§6.3). Editing a body in place makes the
    recorded content_sha256 wrong and flips the store to FROZEN_RECOVERABLE.
    The protocol-legal expression of a rename is a new move() followed by a new
    put() — the chain then records the rename rather than being invalidated by it.
    """
    store = root / ".cyberos" / "memory" / "store"
    if not store.is_dir():
        print("no BRAIN store at .cyberos/memory/store", file=sys.stderr)
        return 2

    fr_id = re.compile(r"(?i)\bfr-([a-z]{2,10})-(\d{3,4})\b")
    ops = 0
    for p in sorted(store.rglob("*.md")):
        rel = p.relative_to(store).as_posix()
        if rel.startswith(("audit/", "exports/", "index/")):
            continue
        body = p.read_text(encoding="utf-8", errors="replace")
        new_rel = fr_id.sub(lambda m: f"TASK-{m.group(1).upper()}-{m.group(2)}"
                            if m.group(0)[0].isupper() else f"task-{m.group(1)}-{m.group(2)}", rel)
        new_body, _ = rewrite(body, rel)
        if new_rel != rel:
            print(json.dumps({"op": "move", "src": rel, "dst": new_rel}))
            ops += 1
        if new_body != body:
            print(json.dumps({
                "op": "put", "path": new_rel, "body": new_body,
                "extra": {"reason": "fr-to-task-rename-epoch"},
            }))
            ops += 1
    print(f"# {ops} ops — pipe into: python3 -m cyberos.writer apply --ndjson -",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
