#!/usr/bin/env python3
"""
migrate_fr_to_task.py — one-wave codemod: feature-request -> task, task -> subtask.

Decisions this script implements (see docs/reviews/task-rename-analysis.md §9):
  D1  the existing task@1 contract (unit of work INSIDE an FR) becomes subtask@1
  D2  all 563 FR IDs are rewritten: FR-<MOD>-<NNN> -> TASK-<MOD>-<NNN>
  D3  archives and audit evidence are rewritten too (pre-1.0, no external consumers)
  D4  one wave

The BRAIN store (.cyberos/memory/store/) is DENIED. It is not a style choice:
the audit ledger is a hash chain (AGENTS.md §6.3) with 252k rows, and every
memory file body's SHA-256 is recorded in a ledger row (§5.3). A byte-level sed
over the store breaks the chain and flips the store to FROZEN. The rename must
be expressed there as move(src,dst)+put(dst,body) through the canonical writer.
See --emit-brain-ops.

Usage:
    python3 scripts/migrate_fr_to_task.py                 # dry run, summary only
    python3 scripts/migrate_fr_to_task.py --show-files    # dry run, list files per rule
    python3 scripts/migrate_fr_to_task.py --apply         # rewrite contents + git mv paths
    python3 scripts/migrate_fr_to_task.py --verify        # assert zero residue post-apply
    python3 scripts/migrate_fr_to_task.py --emit-brain-ops > brain-rename.ndjson
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Deny-list — paths the codemod must never touch.
# CI asserts zero diff under every one of these after --apply.
# ─────────────────────────────────────────────────────────────────────────────
DENY_PREFIXES = (
    ".cyberos/",            # BRAIN store (hash chain, protocol-immutable) + regenerated payload
    "tools/caf/",           # CAF owns "BACKLOG.md" and "Task table" with unrelated meanings;
                            # 63 golden eval fixtures would be corrupted by a blind rewrite
    "dist/",                # build output, regenerated by tools/cyberos-init/build.sh
    ".vercel-out/",         # deploy output
    "docs/status/data/",    # 507 generated per-FR data files, regenerated by the docs-site build
    ".ruff_cache/",
    ".git/",
    "node_modules/",
    "scripts/migrate_fr_to_task.py",   # this file
)

# ─────────────────────────────────────────────────────────────────────────────
# SEALED held-out acceptance tests. chmod 444 via `awh lock modules/memory/tests`
# (tools/awh/harness/stage0_verification/readonly.py), explicitly so that "the
# authoring agent cannot edit the bar it is graded against". There is no `awh
# unlock` verb — the seal is one-way by design, and breaking it must be a
# deliberate human act, not a line buried in a 2,499-file codemod.
#
# The codemod therefore refuses to touch them. It REPORTS them instead, so the
# edits are made by a human, reviewed, and recorded. `--verify` will flag the FR
# ids left inside them as residue; that is correct and intentional.
#
# Two of the three are docstring-only and cosmetic. The third is not:
#   modules/memory/tests/test_claude_code_hook.py:82
#       assert fm["source"] == "fr-memory-109"
#   modules/memory/cyberos/core/claude_code_hook.py:90
#       "source": "fr-memory-109",
# That is a coupled emitter/assertion pair on a value PERSISTED into memory-file
# frontmatter. Rewriting both keeps the test green — which is exactly the pattern
# the seal exists to catch. Decide it consciously. See --sealed.
# ─────────────────────────────────────────────────────────────────────────────
SEALED_PATHS = (
    "modules/memory/tests/test_claude_code_hook.py",
    "modules/memory/tests/test_memory_sync.py",
    "modules/memory/tests/test_sync_class.py",
)

# Binary / non-text extensions we never rewrite.
# NOTE: .svg is deliberately NOT here. SVG is text, and four architecture diagrams
# (modules/skill/docs/assets/diagrams/, modules/skill/assets/) have skill names
# baked into <text> nodes. Excluding them in pass 1 left the diagrams rendering
# `cuo/cpo/feature-request-author` after the rename. New names are shorter, so no
# label overflow.
SKIP_SUFFIXES = (
    ".png", ".jpg", ".jpeg", ".ico", ".woff", ".woff2", ".ttf",
    ".zip", ".gz", ".zst", ".binlog", ".sqlite", ".lock", ".pdf",
)

# ─────────────────────────────────────────────────────────────────────────────
# Content rules, applied IN ORDER. Longest / most-specific identifiers first so
# a short pattern cannot eat a long one.
#
# Ordering note: pass 1 frees the word `task` by moving the existing task@1
# contract to subtask@1. Only after that does pass 5 introduce `task@1` as the
# new name for feature_request@1. Running these out of order silently collapses
# the two contracts into one.
#
# Word-boundary note: \btask\b does NOT match inside "subtask" or "sub_tasks"
# (b/t and _/t are both word characters, so there is no boundary). That is what
# makes the subtask-first ordering safe.
# ─────────────────────────────────────────────────────────────────────────────
RULES: list[tuple[str, str, str]] = [
    # ── Pass 1: free the word. The existing task@1 becomes subtask@1. ────────
    ("free-word:contract-literal",   r"\btask@1\b",                    "subtask@1"),
    ("free-word:contract-id",        r"^contract_id: task$",           "contract_id: subtask"),
    ("free-word:contract-path",      r"contracts/task\b",              "contracts/subtask"),
    ("free-word:runner-module",      r"\bfr_with_tasks\b",             "task_with_subtasks"),
    ("free-word:runner-skill-id",    r"\bfr-with-tasks\b",             "task-with-subtasks"),
    ("free-word:runner-class",       r"\bFrWithTasksRunner\b",         "TaskWithSubtasksRunner"),
    ("free-word:frontmatter-field",  r"\bsub_tasks\b",                 "subtasks"),
    # subtask id sub-format: FR-007-T-03 -> TASK-007-S-03 (the -T- infix would
    # read as "task" inside a TASK- id; -S- is unambiguous).
    ("free-word:subtask-id",         r"\bFR-(\d+)-T-(\d{2})\b",        r"TASK-\1-S-\2"),

    # ── Pass 2: FR IDs. D2 = full rewrite. ──────────────────────────────────
    ("id:fr-module-num",             r"\bFR-([A-Z]{2,10})-(\d{3,4})\b", r"TASK-\1-\2"),
    # lowercase form appears in generated filenames (impl-plan-fr-mcp-003.md)
    ("id:fr-module-num-lower",       r"\bfr-([a-z]{2,10})-(\d{3,4})\b", r"task-\1-\2"),

    # ── Pass 3: artefact + skill + command identifiers. ──────────────────────
    ("artefact:feature-request-1",   r"\bfeature_request@1\b",         "task@1"),
    ("artefact:fr-manifest",         r"\bfr-manifest@2\b",             "task-manifest@1"),
    ("skill:fr-author",              r"\bfeature-request-author\b",    "task-author"),
    ("skill:fr-audit",               r"\bfeature-request-audit\b",     "task-audit"),
    ("cmd:ship",                     r"\bship-feature-requests\b",     "ship-tasks"),
    ("cmd:create",                   r"\bcreate-feature-requests\b",   "create-tasks"),

    # ── Pass 4: paths. Must run AFTER the skill/command rules above, because
    #     "docs/feature-requests/" and "contracts/feature-request/" share a stem
    #     with the skill names. ─────────────────────────────────────────────────
    ("path:docs-dir",                r"docs/feature-requests\b",       "docs/tasks"),
    ("path:contract-dir",            r"contracts/feature-request\b",   "contracts/task"),

    # ── Pass 5: frontmatter fields carrying FR IDs. ──────────────────────────
    ("field:related-frs",            r"\brelated_frs\b",               "related_tasks"),

    # ── Pass 5b: code identifiers. D5 = task_id, module-scoped.
    #     Safe at the rename site: `fr_id` appears only in modules/cuo,
    #     modules/skill, scripts/ and tools/ — never in services/mcp-gateway
    #     (which owns mcp_tasks.task_id) or tools/awh (eval task_id). The
    #     overload is repo-wide and semantic, not a shadowing bug. It is
    #     recorded in an ADR and enforced by check_sep986_naming.sh. ─────────
    ("ident:fr-id",                  r"\bfr_id\b",                     "task_id"),
    ("ident:fr-row",                 r"\bfr_row\b",                    "task_row"),
    ("ident:FrRow",                  r"\bFrRow\b",                     "TaskRow"),
    ("ident:FR_ROW_RE",              r"\b_FR_ROW_RE\b",                "_TASK_ROW_RE"),
    ("ident:FR_ID_RE",               r"\b_FR_ID_RE\b",                 "_TASK_ID_RE"),
    ("ident:frs-var",                r"\bfrs\b(?=\s*[:=\)\],])",       "tasks"),

    # ── Pass 6: remaining identifiers, then prose. ───────────────────────────
    #
    # PASS-2 ADDITIONS. The first run left ~90 sites behind because `_` is a word
    # character, so `\bfeature_request\b` never matched INSIDE a longer snake_case
    # identifier:
    #     _apply_feature_request_audit      (cuo/core/applier.py — function name)
    #     feature_request_audit:            (backlog-state-update envelope FIELD —
    #                                        required by the BSU rubric for the
    #                                        draft -> ready_to_implement transition)
    #     feature_request_author_validates  (skill-broker test fn names)
    # Handle the compounds explicitly, longest first, then drop the boundary.
    ("ident:apply-fr-audit-fn",      r"_apply_feature_request_audit",  "_apply_task_audit"),
    ("ident:fr-audit-field",         r"feature_request_audit",         "task_audit"),
    ("ident:fr-author-field",        r"feature_request_author",        "task_author"),
    ("ident:feature-request-snake",  r"feature_request",               "task"),

    ("ident:feature-requests-kebab", r"\bfeature-requests\b",          "tasks"),
    ("ident:feature-request-kebab",  r"\bfeature-request\b",           "task"),

    # Prose. The first run missed hyphenated Title Case ("Phase F - Feature-Request
    # Authoring") and sentence case ("Feature request — engineering-spec@1", the
    # user-visible kind label on every rendered docs page).
    ("prose:Feature-Requests-hyph",  r"\bFeature-Requests\b",          "Tasks"),
    ("prose:Feature-Request-hyph",   r"\bFeature-Request\b",           "Task"),
    ("prose:Feature-Requests",       r"\bFeature Requests\b",          "Tasks"),
    ("prose:Feature-requests-sent",  r"\bFeature requests\b",          "Tasks"),
    ("prose:Feature-Request",        r"\bFeature Request\b",           "Task"),
    ("prose:Feature-request-sent",   r"\bFeature request\b",           "Task"),
    ("prose:feature-requests",       r"\bfeature requests\b",          "tasks"),
    ("prose:feature-request",        r"\bfeature request\b",           "task"),
]

# The bare `FR` abbreviation is NOT in RULES. It is 2 characters and appears
# inside unrelated words, inside the FR-<MOD>-<NNN> ids handled above, and in
# third-party prose. --residue reports every remaining site for a human pass.
RESIDUE_PATTERNS = [
    ("bare-FR-abbrev",  re.compile(r"(?<![A-Za-z0-9_-])FRs?(?![A-Za-z0-9_-])")),
    ("fr-lowercase",    re.compile(r"\bfr_id\b|\bfr_row\b|\bFrRow\b|\b_FR_ROW_RE\b|\b_FR_ID_RE\b")),
    ("leftover",        re.compile(r"(?i)feature[-_ ]request")),
]

# Path renames (git mv). Applied after content rewrite.
PATH_RENAMES = [
    ("docs/feature-requests",                    "docs/tasks"),
    ("modules/skill/contracts/task",             "modules/skill/contracts/subtask"),
    ("modules/skill/contracts/feature-request",  "modules/skill/contracts/task"),
    ("modules/skill/feature-request-author",     "modules/skill/task-author"),
    ("modules/skill/feature-request-audit",      "modules/skill/task-audit"),
    ("modules/skill/runners/fr_with_tasks.py",   "modules/skill/runners/task_with_subtasks.py"),
    ("modules/cuo/chief-technology-officer/workflows/ship-feature-requests.md",
     "modules/cuo/chief-technology-officer/workflows/ship-tasks.md"),
    ("tools/cyberos-init/plugin/commands/create-feature-requests.md",
     "tools/cyberos-init/plugin/commands/create-tasks.md"),
    ("scripts/migrate_fr_layout.py",             "scripts/migrate_task_layout.py"),
    ("scripts/repair_fr_yaml.py",                "scripts/repair_task_yaml.py"),
    ("scripts/rebaseline_fr_status.py",          "scripts/rebaseline_task_status.py"),
    ("scripts/awh_goldenset_from_fr.py",         "scripts/awh_goldenset_from_task.py"),
    ("tools/cyberos-init/lib/fr-migrate.sh",     "tools/cyberos-init/lib/task-migrate.sh"),
    ("tools/docs-site/render-fr-catalog.mjs",    "tools/docs-site/render-task-catalog.mjs"),
    ("tools/docs-site/render-fr-pages.mjs",      "tools/docs-site/render-task-pages.mjs"),
]

# ─────────────────────────────────────────────────────────────────────────────
# IDEMPOTENCY GUARD.
#
# Three rules are ONE-SHOT. They free the word `task` by demoting the old
# task@1 contract to subtask@1. Once pass 1 has run, `task@1` means the NEW
# thing (the former feature_request@1). Re-running them would demote THAT to
# subtask@1 and collapse both contracts into one — silently, across 216 sites.
#
# Every other rule is idempotent: its left-hand side no longer exists after the
# first run, so a second pass is a no-op.
#
# The guard keys off the on-disk marker that pass 1 leaves behind.
# ─────────────────────────────────────────────────────────────────────────────
ONE_SHOT_RULES = frozenset({
    "free-word:contract-literal",   # task@1 -> subtask@1
    "free-word:contract-id",        # contract_id: task -> subtask
    "free-word:contract-path",      # contracts/task -> contracts/subtask
})

# The PATH rename is one-shot for the same reason, and guarding only the content
# rules is not enough. Learned the hard way on the pass-2 run: `contracts/task ->
# contracts/subtask` re-fired and swallowed the NEW task contract into
# contracts/subtask/task/, taking STATUS-REFERENCE.md with it and breaking
# build.sh. An "is the source absent?" check does NOT catch this — the source very
# much exists, it is just a different thing now.
ONE_SHOT_PATH_RENAMES = frozenset({
    ("modules/skill/contracts/task", "modules/skill/contracts/subtask"),
})


def word_already_freed(root: Path) -> bool:
    """True once pass 1 has demoted the old task@1 contract to subtask@1."""
    return (root / "modules" / "skill" / "contracts" / "subtask").is_dir()


COMPILED_ALL = [(name, re.compile(pat, re.MULTILINE), rep) for name, pat, rep in RULES]
COMPILED = COMPILED_ALL   # rebound in main() once the repo root is known


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return Path(out.stdout.strip())


def tracked_files(root: Path) -> list[str]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=root, capture_output=True, text=True, check=True,
    )
    return [p for p in out.stdout.split("\0") if p]


# ─────────────────────────────────────────────────────────────────────────────
# Tracked SYMLINKS. git ls-files lists them like ordinary paths, so a naive
# read_text() either explodes (IsADirectoryError, when the link points at a
# directory) or — far worse — writes THROUGH the link into a target that is
# itself tracked and already rewritten.
#
# This repo has six:
#   AGENTS.md                                 -> modules/memory/cyberos/data/AGENTS.md
#   CLAUDE.md                                 -> modules/memory/cyberos/data/AGENTS.md
#   .codex/skills/ship-feature-requests       -> ../../.cyberos/plugin/skills/ship-feature-requests
#   .commandcode/skills/ship-feature-requests -> (same)
#   .grok/skills/ship-feature-requests        -> (same)
#   .opencode/skill/ship-feature-requests     -> (same)
#
# AGENTS.md and CLAUDE.md point at the SAME file. Planning three edits that all
# write to one target is how you corrupt the memory protocol: the third read
# would see the already-rewritten body and fire the one-shot `task@1 ->
# subtask@1` rule on it. The two-phase apply (plan everything, then write)
# happens to prevent this, but do not rely on that — skip links outright. Their
# targets are tracked separately and get rewritten on their own.
# ─────────────────────────────────────────────────────────────────────────────
SYMLINK_RENAMES = (
    (".codex/skills",       "ship-feature-requests", "ship-tasks"),
    (".commandcode/skills", "ship-feature-requests", "ship-tasks"),
    (".grok/skills",        "ship-feature-requests", "ship-tasks"),
    (".opencode/skill",     "ship-feature-requests", "ship-tasks"),
    (".claude/skills",      "ship-feature-requests", "ship-tasks"),   # gitignored, fix anyway
)


def in_scope(rel: str) -> bool:
    if any(rel.startswith(p) for p in DENY_PREFIXES):
        return False
    if rel in SEALED_PATHS:
        return False
    if any(rel.endswith(s) for s in SKIP_SUFFIXES):
        return False
    return True


def fix_symlinks(root: Path) -> None:
    """Retarget the agent-tool skill symlinks: ship-feature-requests -> ship-tasks.

    These are how Claude Code, Codex, Grok, opencode and commandcode discover the
    workflow. Four of the five are TRACKED. Leave them and every agent keeps
    resolving a skill name that no longer exists the moment build.sh regenerates
    the payload.
    """
    print("\n--- agent skill symlinks ---")
    for d, old, new in SYMLINK_RENAMES:
        old_p = root / d / old
        new_p = root / d / new
        if not old_p.is_symlink():
            print(f"skip (absent)  {d}/{old}")
            continue
        target = __import__("os").readlink(old_p)
        new_target = target.replace(old, new)
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", f"{d}/{old}"],
            cwd=root, capture_output=True, text=True,
        ).returncode == 0
        if new_p.is_symlink() or new_p.exists():
            print(f"skip (done)    {d}/{new} already exists")
            continue
        if tracked:
            subprocess.run(["git", "rm", "-q", "--cached", f"{d}/{old}"], cwd=root, check=True)
        old_p.unlink()
        new_p.symlink_to(new_target)
        if tracked:
            # -f is REQUIRED: these agent dirs are gitignored, and the old links
            # were force-added. Without -f, git refuses and the run dies here,
            # halfway through the symlink set.
            subprocess.run(["git", "add", "-f", f"{d}/{new}"], cwd=root, check=True)
        print(f"retargeted     {d}/{new} -> {new_target}"
              f"{'  (tracked)' if tracked else '  (gitignored)'}")
    print("\n  Also update the managed block in .gitignore (it names the OLD paths),")
    print("  and rebuild the payload so the symlink targets actually exist:")
    print("      bash tools/cyberos-init/build.sh")


def report_sealed(root: Path) -> None:
    """Show, but never write, the edits the codemod would make to sealed tests."""
    print("\n--- SEALED held-out tests (codemod refuses to write; do these by hand) ---")
    for rel in SEALED_PATHS:
        p = root / rel
        if not p.exists():
            print(f"  absent: {rel}")
            continue
        src = p.read_text(encoding="utf-8")
        new, hits = rewrite(src)
        if not hits:
            print(f"  clean:  {rel}")
            continue
        print(f"\n  {rel}   ({sum(hits.values())} edits)")
        for i, (a, b) in enumerate(zip(src.splitlines(), new.splitlines()), 1):
            if a != b:
                kind = "DATA" if not a.lstrip().startswith(('"""', "#", "'''")) else "docstring"
                print(f"    L{i} [{kind}]")
                print(f"      - {a.strip()[:96]}")
                print(f"      + {b.strip()[:96]}")
    print("""
  To apply, as a deliberate human act:
      chmod u+w modules/memory/tests/test_claude_code_hook.py \\
                modules/memory/tests/test_memory_sync.py \\
                modules/memory/tests/test_sync_class.py
      # edit the lines above by hand, then re-seal:
      python -m awh lock modules/memory/tests
      git commit -m "test(memory): unseal held-out tests for fr->task rename, re-sealed"

  Before you touch test_claude_code_hook.py L82, decide the DATA question:
  claude_code_hook.py:90 writes `"source": "fr-memory-109"` into memory-file
  frontmatter. The BRAIN has 0 files carrying it today, so rewriting is free NOW.
  If the hook had ever run, you would have persisted data on one vocabulary and
  new code on another, with the BRAIN deny-listed from this codemod. Either
  rewrite both and note it, or leave `source` as a frozen provenance tag.""")


def rewrite(text: str) -> tuple[str, Counter]:
    hits: Counter = Counter()
    for name, pat, rep in COMPILED:
        text, n = pat.subn(rep, text)
        if n:
            hits[name] += n
    return text, hits


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true", help="write changes and git mv paths")
    ap.add_argument("--show-files", action="store_true", help="list files touched per rule")
    ap.add_argument("--verify", action="store_true", help="assert zero residue; exit 1 if any")
    ap.add_argument("--residue", action="store_true", help="report sites the rules cannot reach")
    ap.add_argument("--emit-brain-ops", action="store_true",
                    help="emit NDJSON move/put ops for the BRAIN store (do not sed it)")
    ap.add_argument("--sealed", action="store_true",
                    help="show the edits the codemod refuses to make to sealed held-out tests")
    ap.add_argument("--fix-symlinks", action="store_true",
                    help="retarget the agent skill symlinks only (no dirty-tree guard)")
    args = ap.parse_args()

    root = repo_root()

    if args.fix_symlinks:
        fix_symlinks(root)
        return 0

    # ── Idempotency guard: disarm the one-shot rules once pass 1 has run. ───
    global COMPILED
    freed = word_already_freed(root)
    if freed:
        COMPILED = [t for t in COMPILED_ALL if t[0] not in ONE_SHOT_RULES]
        print("note: contracts/subtask/ exists -> pass 1 already ran.")
        print("      one-shot rules DISARMED (they would demote the new task@1 "
              "to subtask@1):")
        for r in sorted(ONE_SHOT_RULES):
            print(f"        {r}")
        print()

    files = [f for f in tracked_files(root) if in_scope(f)]

    if args.emit_brain_ops:
        return emit_brain_ops(root)

    if args.sealed:
        report_sealed(root)
        return 0

    # ── Guard 1: refuse to apply to a dirty tree. ───────────────────────────
    # `git checkout -- .` must be a valid, complete undo. If the tree already
    # has uncommitted work, a failed apply cannot be cleanly reverted.
    if args.apply:
        dirty = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=no"],
            cwd=root, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if dirty:
            print("REFUSING TO APPLY: working tree is dirty.", file=sys.stderr)
            print("Commit or stash first, so `git checkout -- .` is a clean undo.\n",
                  file=sys.stderr)
            print(dirty, file=sys.stderr)
            return 2

    total: Counter = Counter()
    touched: dict[str, list[str]] = {}
    residue: Counter = Counter()
    residue_files: dict[str, set[str]] = {}
    plan: list[tuple[Path, str]] = []   # (path, new_content) — nothing is written yet

    # ── Phase 1: plan every edit in memory. Write nothing. ──────────────────
    skipped_links = 0
    for rel in files:
        path = root / rel
        # Never read or write through a symlink. See SYMLINK_RENAMES above:
        # AGENTS.md and CLAUDE.md both point at modules/memory/cyberos/data/AGENTS.md,
        # and four skill links point at directories. Their targets are tracked
        # separately and get rewritten on their own.
        if path.is_symlink():
            skipped_links += 1
            continue
        try:
            src = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, FileNotFoundError, IsADirectoryError):
            continue

        new, hits = rewrite(src)

        if args.residue or args.verify:
            probe = src if args.verify else new
            for rname, rpat in RESIDUE_PATTERNS:
                n = len(rpat.findall(probe))
                if n:
                    residue[rname] += n
                    residue_files.setdefault(rname, set()).add(rel)

        if hits:
            total.update(hits)
            for k in hits:
                touched.setdefault(k, []).append(rel)
            plan.append((path, new))

    changed_files = len(plan)

    # ── Guard 2: pre-flight writability. Abort BEFORE the first write. ──────
    # A crash halfway through leaves a half-renamed repo, which is far worse
    # than not starting. Learned the hard way: an ACL-restricted file killed
    # the first run at file ~1349 of 2498.
    if args.apply:
        unwritable = [p for p, _ in plan if not p.parent.is_dir() or (
            p.exists() and not __import__("os").access(p, __import__("os").W_OK))]
        if unwritable:
            print(f"REFUSING TO APPLY: {len(unwritable)} planned files are not writable.",
                  file=sys.stderr)
            for p in unwritable[:20]:
                print(f"  {p.relative_to(root)}", file=sys.stderr)
            return 2

    # ── Phase 2: commit the plan to disk. ───────────────────────────────────
    if args.apply:
        for path, new in plan:
            path.write_text(new, encoding="utf-8")

    mode = "APPLY" if args.apply else ("VERIFY" if args.verify else "DRY RUN")
    print(f"=== migrate_fr_to_task — {mode} ===")
    print(f"in-scope tracked files : {len(files)}")
    print(f"symlinks skipped       : {skipped_links}  (targets rewritten separately)")
    print(f"files with edits       : {changed_files}")
    print(f"total substitutions    : {sum(total.values())}\n")

    print(f"{'rule':32} {'hits':>7}  files")
    for name, _p, _r in RULES:
        n = total.get(name, 0)
        if n:
            print(f"{name:32} {n:7}  {len(touched.get(name, []))}")
            if args.show_files:
                for f in sorted(touched[name])[:12]:
                    print(f"{'':34}   {f}")
                extra = len(touched[name]) - 12
                if extra > 0:
                    print(f"{'':34}   ... +{extra} more")

    if args.residue or args.verify:
        print(f"\n--- residue (needs a human pass) ---")
        if not residue:
            print("none")
        for rname, n in residue.most_common():
            print(f"{rname:32} {n:7}  {len(residue_files[rname])} files")
            if args.show_files:
                for f in sorted(residue_files[rname])[:10]:
                    print(f"{'':34}   {f}")

    if args.apply:
        print("\n--- path renames (git mv) ---")
        for src, dst in PATH_RENAMES:
            if freed and (src, dst) in ONE_SHOT_PATH_RENAMES:
                print(f"skip (ONE-SHOT, already ran)  {src} -> {dst}")
                continue
            s, d = root / src, root / dst
            if not s.exists():
                print(f"skip (absent)  {src}")
                continue
            if d.exists():
                # git mv into an existing directory NESTS instead of failing.
                # That is how contracts/task ended up inside contracts/subtask/task/.
                print(f"REFUSING       {src} -> {dst}  (destination exists; would nest)")
                continue
            d.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(["git", "mv", src, dst], cwd=root, check=True)
            print(f"moved          {src} -> {dst}")

        # ── The 563 per-spec directories: docs/tasks/<mod>/FR-MOD-NNN-slug/ ──
        print("\n--- spec directory renames (FR-* -> TASK-*) ---")
        tasks_root = root / "docs" / "tasks"
        moved = 0
        if tasks_root.is_dir():
            # Deepest-first so a parent rename cannot invalidate a child path.
            cands = sorted(
                (p for p in tasks_root.rglob("*") if p.is_dir() and p.name.startswith("FR-")),
                key=lambda p: len(p.parts), reverse=True,
            )
            for p in cands:
                new_name = re.sub(r"^FR-", "TASK-", p.name)
                subprocess.run(
                    ["git", "mv", str(p.relative_to(root)),
                     str((p.parent / new_name).relative_to(root))],
                    cwd=root, check=True,
                )
                moved += 1
        print(f"renamed {moved} spec directories")

        fix_symlinks(root)

        print("\n--- next, by hand ---")
        print("  1. the 13 agent-config files (.cursorrules, .windsurfrules, .grok/GROK.md,")
        print("     .github/copilot-instructions.md, .agents/rules/, .cursor/rules/, AGENTS.md,")
        print("     CLAUDE.md, GEMINI.md, .gitignore managed block, .githooks/pre-commit)")
        print("  2. the bare-FR prose pass (see --residue; 2-char token, needs review)")
        print("  3. .git-blame-ignore-revs <- sha of this commit")
        print("  4. --emit-brain-ops | python3 -m cyberos.writer apply   (never sed the store)")

    if args.verify and residue:
        print("\nVERIFY FAILED: residue remains.")
        return 1
    return 0


def emit_brain_ops(root: Path) -> int:
    """The BRAIN store cannot be sed'd. Emit protocol-legal move+put ops instead.

    Every memory file body's SHA-256 is recorded in an audit row (AGENTS.md §5.3),
    and the ledger is a hash chain (§6.3). Editing a body in place makes the
    recorded content_sha256 wrong and flips the store to FROZEN_RECOVERABLE.
    The protocol-legal expression of a rename is a new move() followed by a new
    put() — the chain then records the rename rather than being invalidated by it.
    """
    store = root / ".cyberos" / "memory" / "store"
    if not store.is_dir():
        print("no BRAIN store at .cyberos/memory/store", file=sys.stderr)
        return 2

    fr_id = re.compile(r"(?i)\bfr-([a-z]{2,10})-(\d{3,4})\b")
    ops = 0
    for p in sorted(store.rglob("*.md")):
        rel = p.relative_to(store).as_posix()
        if rel.startswith(("audit/", "exports/", "index/")):
            continue
        body = p.read_text(encoding="utf-8", errors="replace")
        new_rel = fr_id.sub(lambda m: f"TASK-{m.group(1).upper()}-{m.group(2)}"
                            if m.group(0)[0].isupper() else f"task-{m.group(1)}-{m.group(2)}", rel)
        new_body, _ = rewrite(body)
        if new_rel != rel:
            print(json.dumps({"op": "move", "src": rel, "dst": new_rel}))
            ops += 1
        if new_body != body:
            print(json.dumps({
                "op": "put", "path": new_rel, "body": new_body,
                "extra": {"reason": "fr-to-task-rename-epoch"},
            }))
            ops += 1
    print(f"# {ops} ops — pipe into: python3 -m cyberos.writer apply --ndjson -",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
