#!/usr/bin/env bash
# build-pack.sh - assemble a self-contained, portable "FR pack" from the canonical
# CyberOS sources into dist/fr-pack/. The result runs the ship-feature-requests
# workflow in ANY repo, with NO CyberOS clone required.
#
# It is best-effort: the three normative docs are always vendored (doc-driven mode,
# which works everywhere). The author/audit skill bodies and the caf tooling are
# vendored only if they exist in this repo (full mode). Whatever is missing degrades
# to the reduced-profile floor (the target repo's own build/lint/test + coverage +
# code review + the two human-acceptance gates).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"                 # tools/fr-pack
repo="$(cd "$here/../.." && pwd)"                      # cyberos repo root
out="${1:-$repo/dist/fr-pack}"                         # dist dir (arg 1 overrides)

echo "fr-pack: assembling into $out"
rm -rf "$out"
mkdir -p "$out/machine" "$out/machine/skills" "$out/gates" "$out/gates/caf"

# --- always: the three normative docs (doc-driven mode works with just these) ---
cp "$repo/modules/cuo/chief-technology-officer/workflows/ship-feature-requests.md" "$out/machine/ship-feature-requests.md"
cp "$repo/modules/cuo/EXECUTION-DISCIPLINE.md"                                       "$out/machine/EXECUTION-DISCIPLINE.md"
cp "$repo/modules/skill/contracts/feature-request/STATUS-REFERENCE.md"              "$out/machine/STATUS-REFERENCE.md"

# --- best-effort: author/audit skill bodies (sharpen each workflow step if present) ---
skills="repo-context-map-author repo-context-map-audit architecture-decision-record-author architecture-decision-record-audit edge-case-matrix-author edge-case-matrix-audit mock-contract-test-author mock-contract-test-audit implementation-plan-author implementation-plan-audit observability-injection-author observability-injection-audit backlog-state-update-author backlog-state-update-audit code-review-author code-review-audit coverage-gate-author coverage-gate-audit feature-request-audit"
vendored_skills=0
for s in $skills; do
  if [ -d "$repo/modules/skill/$s" ]; then
    cp -R "$repo/modules/skill/$s" "$out/machine/skills/$s"
    vendored_skills=$((vendored_skills + 1))
  fi
done

# --- best-effort: caf gate tooling (full deterministic code-audit floor if present) ---
caf_vendored="no"
if [ -f "$repo/scripts/caf_gate.sh" ] && [ -d "$repo/tools/caf" ]; then
  cp "$repo/scripts/caf_gate.sh" "$out/gates/caf/caf_gate.sh"
  cp -R "$repo/tools/caf" "$out/gates/caf/caf"
  caf_vendored="yes"
fi

# --- always: the portable runtime (scripts, templates, channels, docs) ---
cp "$here/init.sh"            "$out/init.sh"
cp "$here/bootstrap.sh"       "$out/bootstrap.sh"
cp "$here/gates/run-gates.sh" "$out/gates/run-gates.sh"
cp -R "$here/templates"       "$out/templates"
cp -R "$here/plugin"          "$out/plugin"
cp -R "$here/ci"              "$out/ci"
cp "$here/Dockerfile"         "$out/Dockerfile"
cp "$here/README.md"          "$out/README.md"
chmod +x "$out/init.sh" "$out/bootstrap.sh" "$out/gates/run-gates.sh" 2>/dev/null || true

# make the plugin self-contained: carry the machine docs so the bundled skill works standalone
cp -R "$out/machine" "$out/plugin/skills/ship-feature-requests/machine"

# --- profile + manifest ---
profile="reduced"
[ "$vendored_skills" -gt 0 ] && [ "$caf_vendored" = "yes" ] && profile="full"
ver="$(cd "$repo" && git rev-parse --short HEAD 2>/dev/null || echo unknown)"
cat > "$out/manifest.yaml" <<EOF
# Generated by build-pack.sh - do not edit by hand.
pack: cyberos-fr
built_from_commit: $ver
built_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
profile: $profile          # full = skills + caf vendored; reduced = doc-driven + repo's own gates
vendored:
  normative_docs: 3        # ship-feature-requests, EXECUTION-DISCIPLINE, STATUS-REFERENCE
  author_audit_skills: $vendored_skills
  caf_tooling: $caf_vendored
notes: >
  Doc-driven mode always works. Missing skills/caf degrade to the reduced-profile floor:
  the target repo's own build/lint/test + coverage + code review + the two human gates.
EOF

echo "fr-pack: done. profile=$profile skills=$vendored_skills caf=$caf_vendored"
echo "fr-pack: portable bundle is $out (copy it, submodule it, curl it, or load plugin/ as a Claude plugin)"
