#!/usr/bin/env python3
"""
cyberos_project_index.py — auto-generate / refresh `project-index.md` inside a
planning project folder.

Batch D (2026-05-12). The project-index is a one-page dashboard for a project:
- pitch + spec inputs (PRD/SRS/spec-file paths)
- FR index table (id, title, task counts, status)
- profile + creation date

Designed to be re-runnable: regenerates the file each chain run from whatever
FRs exist in the folder. Hand-written sections (between `<!-- BEGIN human -->`
and `<!-- END human -->` markers) are preserved across regenerations.

NOT the same as `project_brief@1` (which is human-authored before planning
begins). This is a downstream auto-generated dashboard.

Usage:
  cyberos project-index <project_folder>
  cyberos project-index <project_folder> --manifest chain-manifest.json
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from cyberos_fr_parser import parse_fr

ICT = timezone(timedelta(hours=7))

_HUMAN_MARKER_BEGIN = "<!-- BEGIN human-edited -->"
_HUMAN_MARKER_END = "<!-- END human-edited -->"


def collect_project_frs(project_dir: Path) -> list[dict]:
    """Walk project folder for FR-*.md files (ignores .legacy.bak / .placeholder)."""
    out = []
    for md in sorted(project_dir.glob("FR-*.md")):
        if md.suffix == ".bak" or ".placeholder" in md.name or md.name.endswith(".legacy.bak"):
            continue
        try:
            out.append(parse_fr(md))
        except Exception:
            continue
    return out


def read_manifest(project_dir: Path) -> dict:
    mf = project_dir / "chain-manifest.json"
    if mf.exists():
        try:
            return json.loads(mf.read_text())
        except Exception:
            return {}
    return {}


def extract_human_section(existing_text: str) -> str:
    """Pull the previously-written human-edited block, if any."""
    m = re.search(
        re.escape(_HUMAN_MARKER_BEGIN) + r"(.*?)" + re.escape(_HUMAN_MARKER_END),
        existing_text, re.S
    )
    return m.group(1).strip() if m else ""


def render(project_dir: Path, manifest: dict, frs: list[dict], human_block: str) -> str:
    slug = manifest.get("slug") or project_dir.name
    title = slug.replace("-", " ").title() if not manifest.get("pitch_first_120") else manifest["pitch_first_120"]
    if len(title) > 80:
        title = title[:77] + "…"
    now = datetime.now(ICT).isoformat(timespec="seconds")

    lines = []
    lines.append("---")
    lines.append(f"project_slug: {slug}")
    lines.append(f"generated_at: {now}")
    lines.append(f"profile: {manifest.get('profile', 'solo')}")
    lines.append(f"authored_by: cyberos-chain")
    lines.append("artifact_kind: project_index")
    lines.append("---")
    lines.append("")
    lines.append(f"# {title}")
    lines.append("")
    lines.append("> Auto-generated by `cyberos chain run`. Re-runs regenerate the FR table"
                 " from disk. Hand-edited content inside the `<!-- BEGIN human-edited -->`"
                 " block below is preserved across regenerations.")
    lines.append("")

    # Pitch
    pitch = manifest.get("pitch_first_120")
    if pitch:
        lines.append("## Pitch")
        lines.append("")
        lines.append(f"> {pitch}")
        lines.append("")

    # Inputs
    inputs = []
    if manifest.get("prd_file"):
        inputs.append(("PRD", manifest["prd_file"]))
    if manifest.get("srs_file"):
        inputs.append(("SRS", manifest["srs_file"]))
    if manifest.get("spec_file"):
        inputs.append(("Spec", manifest["spec_file"]))
    if inputs:
        lines.append("## Spec inputs")
        lines.append("")
        for label, path in inputs:
            lines.append(f"- **{label}:** `{path}`")
        lines.append("")

    # FR table
    lines.append("## Feature Requests")
    lines.append("")
    if not frs:
        lines.append("_No FRs in this project folder yet. Run `cyberos chain run --pitch \"...\"` to author one._")
    else:
        lines.append("| FR | Title | Tasks | Sizing | Status | File |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for fr in frs:
            sizes = {"S": 0, "M": 0, "L": 0, "XL": 0}
            for t in fr["tasks"]:
                sz = t.get("sizing", "?")
                if sz in sizes:
                    sizes[sz] += 1
            sizing_summary = f"{sizes['S']}S+{sizes['M']}M+{sizes['L']}L+{sizes['XL']}XL"
            fr_path = Path(fr["path"]).name
            lines.append(f"| {fr['fr_id']} | {fr['title'][:60]} | {len(fr['tasks'])} | {sizing_summary} | {fr['status']} | `{fr_path}` |")
    lines.append("")

    # Quick commands
    lines.append("## Quick commands")
    lines.append("")
    lines.append("```shell")
    lines.append(f"cd {project_dir}")
    lines.append("cyberos fr list                       # list FRs in this project")
    lines.append("cyberos fr task-graph FR-001          # render task DAG")
    lines.append("cyberos chain status                  # resume + status of chain runs")
    lines.append("```")
    lines.append("")

    # Human-edited block (preserved verbatim)
    lines.append(_HUMAN_MARKER_BEGIN)
    if human_block:
        lines.append(human_block)
    else:
        lines.append("")
        lines.append("## Milestones")
        lines.append("")
        lines.append("_(add your own milestones here — preserved across regenerations.)_")
        lines.append("")
        lines.append("## Notes")
        lines.append("")
        lines.append("_(anything not captured by FRs — risks, vendor choices, links.)_")
        lines.append("")
    lines.append(_HUMAN_MARKER_END)
    lines.append("")

    return "\n".join(lines)


def generate(project_dir: Path) -> dict:
    if not project_dir.is_dir():
        return {"status": "error", "error": f"not a directory: {project_dir}"}
    manifest = read_manifest(project_dir)
    frs = collect_project_frs(project_dir)
    index_path = project_dir / "project-index.md"
    human_block = ""
    if index_path.exists():
        human_block = extract_human_section(index_path.read_text(encoding="utf-8"))
    text = render(project_dir, manifest, frs, human_block)
    index_path.write_text(text, encoding="utf-8")
    return {
        "status": "ok",
        "path": str(index_path),
        "fr_count": len(frs),
        "preserved_human_block_chars": len(human_block),
    }


def main():
    p = argparse.ArgumentParser(description="Auto-generate project-index.md for a project folder (Batch D)")
    p.add_argument("project_dir", help="path to project folder under planning/")
    args = p.parse_args()
    result = generate(Path(args.project_dir).resolve())
    if result["status"] != "ok":
        print(f"error: {result.get('error')}", file=sys.stderr)
        return 1
    print(f"  wrote {result['path']}")
    print(f"  FRs indexed: {result['fr_count']}")
    if result["preserved_human_block_chars"]:
        print(f"  preserved {result['preserved_human_block_chars']} chars of human-edited content")
    return 0


if __name__ == "__main__":
    sys.exit(main())
