#!/usr/bin/env bash
# test_templates_module.sh - FR-TPL-001 §5 suite (t01-t04 -> AC 1-4).
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"; repo="$(cd "$here/../../.." && pwd)"
T="$repo/modules/templates"
PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "  ok   $1"; }
fail() { FAIL=$((FAIL+1)); echo "  FAIL $1: $2"; }

t01_vendored_pinned() {                                                # AC 1
  [ -s "$T/cds/tokens.css" ] && [ -s "$T/cds/glass.css" ] \
    && grep -q "commit | [0-9a-f]\{40\}" "$T/cds/PROVENANCE.md" \
    && grep -q "Generated by @cyberskill/tokens" "$T/cds/tokens.css" \
    && ! grep -riE "https?://(cdn|fonts\.googleapis|unpkg|jsdelivr)" "$T/html" "$T/cds" >/dev/null \
    && ok t01 || fail t01 "vendoring/provenance/CDN check"
}
t02_contract_complete() {                                              # AC 2
  c="$T/contracts/TEMPLATE.md"
  grep -q "{{slot:<name>}}" "$c" && grep -q "{{slot:<name>:html}}" "$c" \
    && grep -q "data-template-id" "$c" && grep -q "&amp;" "$c" && grep -q "file://" "$c" \
    && grep -q 'data-template-id="deliverable@1"' "$T/html/deliverable.html" \
    && grep -q 'data-template-id="status-hub@1"' "$T/html/status-hub.html" \
    && grep -q 'data-template-id="catalog@1"' "$T/html/catalog.html" \
    && ok t02 || fail t02 "contract or template ids incomplete"
}
t03_shells_selfcontained() {                                           # AC 3
  local bad=""
  for f in "$T"/html/*.html; do
    python3 - "$f" "$T/cds/tokens.css" <<'PY' || bad="$bad $(basename "$f")"
import re, sys
shell, tokens = open(sys.argv[1]).read(), open(sys.argv[2]).read()
out = shell.replace("/*{{slot:styles:html}}*/", tokens)
out = re.sub(r"\{\{slot:[a-z_]+:html\}\}", "<p>fixture</p>", out)
out = re.sub(r"\{\{slot:[a-z_]+\}\}", "fixture", out)
assert "{{slot:" not in out
# only relative refs: no external URLs outside comments
assert not re.search(r'(src|href)="https?://', out)
PY
  done
  [ -z "$bad" ] && ok t03 || fail t03 "not self-contained:$bad"
}
t04_token_only() {                                                     # AC 4
  hexes="$(grep -ohE '#[0-9a-fA-F]{3,6}\b' "$T"/html/*.html | wc -l | tr -d ' ')"
  [ "$hexes" -eq 0 ] && grep -q "var(--cs-" "$T/html/deliverable.html" \
    && ok t04 || fail t04 "$hexes hex literals in shells"
}

t01_vendored_pinned; t02_contract_complete; t03_shells_selfcontained; t04_token_only
echo "----"; echo "pass=$PASS fail=$FAIL"; [ "$FAIL" -eq 0 ]
